// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: riva/proto/riva_tts.proto

#include "riva/proto/riva_tts.pb.h"
#include "riva/proto/riva_tts.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace nvidia {
namespace riva {
namespace tts {

static const char* RivaSpeechSynthesis_method_names[] = {
  "/nvidia.riva.tts.RivaSpeechSynthesis/Synthesize",
  "/nvidia.riva.tts.RivaSpeechSynthesis/SynthesizeOnline",
  "/nvidia.riva.tts.RivaSpeechSynthesis/GetRivaSynthesisConfig",
};

std::unique_ptr< RivaSpeechSynthesis::Stub> RivaSpeechSynthesis::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RivaSpeechSynthesis::Stub> stub(new RivaSpeechSynthesis::Stub(channel, options));
  return stub;
}

RivaSpeechSynthesis::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Synthesize_(RivaSpeechSynthesis_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SynthesizeOnline_(RivaSpeechSynthesis_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_GetRivaSynthesisConfig_(RivaSpeechSynthesis_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RivaSpeechSynthesis::Stub::Synthesize(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest& request, ::nvidia::riva::tts::SynthesizeSpeechResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::nvidia::riva::tts::SynthesizeSpeechRequest, ::nvidia::riva::tts::SynthesizeSpeechResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Synthesize_, context, request, response);
}

void RivaSpeechSynthesis::Stub::async::Synthesize(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest* request, ::nvidia::riva::tts::SynthesizeSpeechResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::nvidia::riva::tts::SynthesizeSpeechRequest, ::nvidia::riva::tts::SynthesizeSpeechResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Synthesize_, context, request, response, std::move(f));
}

void RivaSpeechSynthesis::Stub::async::Synthesize(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest* request, ::nvidia::riva::tts::SynthesizeSpeechResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Synthesize_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::nvidia::riva::tts::SynthesizeSpeechResponse>* RivaSpeechSynthesis::Stub::PrepareAsyncSynthesizeRaw(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::nvidia::riva::tts::SynthesizeSpeechResponse, ::nvidia::riva::tts::SynthesizeSpeechRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Synthesize_, context, request);
}

::grpc::ClientAsyncResponseReader< ::nvidia::riva::tts::SynthesizeSpeechResponse>* RivaSpeechSynthesis::Stub::AsyncSynthesizeRaw(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSynthesizeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::nvidia::riva::tts::SynthesizeSpeechResponse>* RivaSpeechSynthesis::Stub::SynthesizeOnlineRaw(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::nvidia::riva::tts::SynthesizeSpeechResponse>::Create(channel_.get(), rpcmethod_SynthesizeOnline_, context, request);
}

void RivaSpeechSynthesis::Stub::async::SynthesizeOnline(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest* request, ::grpc::ClientReadReactor< ::nvidia::riva::tts::SynthesizeSpeechResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::nvidia::riva::tts::SynthesizeSpeechResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_SynthesizeOnline_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::nvidia::riva::tts::SynthesizeSpeechResponse>* RivaSpeechSynthesis::Stub::AsyncSynthesizeOnlineRaw(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::nvidia::riva::tts::SynthesizeSpeechResponse>::Create(channel_.get(), cq, rpcmethod_SynthesizeOnline_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::nvidia::riva::tts::SynthesizeSpeechResponse>* RivaSpeechSynthesis::Stub::PrepareAsyncSynthesizeOnlineRaw(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::nvidia::riva::tts::SynthesizeSpeechResponse>::Create(channel_.get(), cq, rpcmethod_SynthesizeOnline_, context, request, false, nullptr);
}

::grpc::Status RivaSpeechSynthesis::Stub::GetRivaSynthesisConfig(::grpc::ClientContext* context, const ::nvidia::riva::tts::RivaSynthesisConfigRequest& request, ::nvidia::riva::tts::RivaSynthesisConfigResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::nvidia::riva::tts::RivaSynthesisConfigRequest, ::nvidia::riva::tts::RivaSynthesisConfigResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetRivaSynthesisConfig_, context, request, response);
}

void RivaSpeechSynthesis::Stub::async::GetRivaSynthesisConfig(::grpc::ClientContext* context, const ::nvidia::riva::tts::RivaSynthesisConfigRequest* request, ::nvidia::riva::tts::RivaSynthesisConfigResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::nvidia::riva::tts::RivaSynthesisConfigRequest, ::nvidia::riva::tts::RivaSynthesisConfigResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRivaSynthesisConfig_, context, request, response, std::move(f));
}

void RivaSpeechSynthesis::Stub::async::GetRivaSynthesisConfig(::grpc::ClientContext* context, const ::nvidia::riva::tts::RivaSynthesisConfigRequest* request, ::nvidia::riva::tts::RivaSynthesisConfigResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRivaSynthesisConfig_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::nvidia::riva::tts::RivaSynthesisConfigResponse>* RivaSpeechSynthesis::Stub::PrepareAsyncGetRivaSynthesisConfigRaw(::grpc::ClientContext* context, const ::nvidia::riva::tts::RivaSynthesisConfigRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::nvidia::riva::tts::RivaSynthesisConfigResponse, ::nvidia::riva::tts::RivaSynthesisConfigRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetRivaSynthesisConfig_, context, request);
}

::grpc::ClientAsyncResponseReader< ::nvidia::riva::tts::RivaSynthesisConfigResponse>* RivaSpeechSynthesis::Stub::AsyncGetRivaSynthesisConfigRaw(::grpc::ClientContext* context, const ::nvidia::riva::tts::RivaSynthesisConfigRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRivaSynthesisConfigRaw(context, request, cq);
  result->StartCall();
  return result;
}

RivaSpeechSynthesis::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RivaSpeechSynthesis_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RivaSpeechSynthesis::Service, ::nvidia::riva::tts::SynthesizeSpeechRequest, ::nvidia::riva::tts::SynthesizeSpeechResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RivaSpeechSynthesis::Service* service,
             ::grpc::ServerContext* ctx,
             const ::nvidia::riva::tts::SynthesizeSpeechRequest* req,
             ::nvidia::riva::tts::SynthesizeSpeechResponse* resp) {
               return service->Synthesize(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RivaSpeechSynthesis_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< RivaSpeechSynthesis::Service, ::nvidia::riva::tts::SynthesizeSpeechRequest, ::nvidia::riva::tts::SynthesizeSpeechResponse>(
          [](RivaSpeechSynthesis::Service* service,
             ::grpc::ServerContext* ctx,
             const ::nvidia::riva::tts::SynthesizeSpeechRequest* req,
             ::grpc::ServerWriter<::nvidia::riva::tts::SynthesizeSpeechResponse>* writer) {
               return service->SynthesizeOnline(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RivaSpeechSynthesis_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RivaSpeechSynthesis::Service, ::nvidia::riva::tts::RivaSynthesisConfigRequest, ::nvidia::riva::tts::RivaSynthesisConfigResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RivaSpeechSynthesis::Service* service,
             ::grpc::ServerContext* ctx,
             const ::nvidia::riva::tts::RivaSynthesisConfigRequest* req,
             ::nvidia::riva::tts::RivaSynthesisConfigResponse* resp) {
               return service->GetRivaSynthesisConfig(ctx, req, resp);
             }, this)));
}

RivaSpeechSynthesis::Service::~Service() {
}

::grpc::Status RivaSpeechSynthesis::Service::Synthesize(::grpc::ServerContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest* request, ::nvidia::riva::tts::SynthesizeSpeechResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RivaSpeechSynthesis::Service::SynthesizeOnline(::grpc::ServerContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest* request, ::grpc::ServerWriter< ::nvidia::riva::tts::SynthesizeSpeechResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RivaSpeechSynthesis::Service::GetRivaSynthesisConfig(::grpc::ServerContext* context, const ::nvidia::riva::tts::RivaSynthesisConfigRequest* request, ::nvidia::riva::tts::RivaSynthesisConfigResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace nvidia
}  // namespace riva
}  // namespace tts

