// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: riva/proto/riva_audio.proto
// Original file comments:
// SPDX-FileCopyrightText: Copyright (c) 2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: MIT
//
#ifndef GRPC_riva_2fproto_2friva_5faudio_2eproto__INCLUDED
#define GRPC_riva_2fproto_2friva_5faudio_2eproto__INCLUDED

#include "riva/proto/riva_audio.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace nvidia {
namespace riva {

}  // namespace riva
}  // namespace nvidia


#endif  // GRPC_riva_2fproto_2friva_5faudio_2eproto__INCLUDED
