// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: riva/proto/riva_asr.proto
// Original file comments:
// SPDX-FileCopyrightText: Copyright (c) 2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: MIT
//
// Copyright 2019 Google LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//
#ifndef GRPC_riva_2fproto_2friva_5fasr_2eproto__INCLUDED
#define GRPC_riva_2fproto_2friva_5fasr_2eproto__INCLUDED

#include "riva/proto/riva_asr.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace nvidia {
namespace riva {
namespace asr {

//
// The RivaSpeechRecognition service provides two mechanisms for converting
// speech to text.
class RivaSpeechRecognition final {
 public:
  static constexpr char const* service_full_name() {
    return "nvidia.riva.asr.RivaSpeechRecognition";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Recognize expects a RecognizeRequest and returns a RecognizeResponse. This
    // request will block until the audio is uploaded, processed, and a transcript
    // is returned.
    virtual ::grpc::Status Recognize(::grpc::ClientContext* context, const ::nvidia::riva::asr::RecognizeRequest& request, ::nvidia::riva::asr::RecognizeResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::asr::RecognizeResponse>> AsyncRecognize(::grpc::ClientContext* context, const ::nvidia::riva::asr::RecognizeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::asr::RecognizeResponse>>(AsyncRecognizeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::asr::RecognizeResponse>> PrepareAsyncRecognize(::grpc::ClientContext* context, const ::nvidia::riva::asr::RecognizeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::asr::RecognizeResponse>>(PrepareAsyncRecognizeRaw(context, request, cq));
    }
    // StreamingRecognize is a non-blocking API call that allows audio data to be
    // fed to the server in chunks as it becomes available. Depending on the
    // configuration in the StreamingRecognizeRequest, intermediate results can be
    // sent back to the client. Recognition ends when the stream is closed by the
    // client.
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::nvidia::riva::asr::StreamingRecognizeRequest, ::nvidia::riva::asr::StreamingRecognizeResponse>> StreamingRecognize(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::nvidia::riva::asr::StreamingRecognizeRequest, ::nvidia::riva::asr::StreamingRecognizeResponse>>(StreamingRecognizeRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::nvidia::riva::asr::StreamingRecognizeRequest, ::nvidia::riva::asr::StreamingRecognizeResponse>> AsyncStreamingRecognize(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::nvidia::riva::asr::StreamingRecognizeRequest, ::nvidia::riva::asr::StreamingRecognizeResponse>>(AsyncStreamingRecognizeRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::nvidia::riva::asr::StreamingRecognizeRequest, ::nvidia::riva::asr::StreamingRecognizeResponse>> PrepareAsyncStreamingRecognize(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::nvidia::riva::asr::StreamingRecognizeRequest, ::nvidia::riva::asr::StreamingRecognizeResponse>>(PrepareAsyncStreamingRecognizeRaw(context, cq));
    }
    // Enables clients to request the configuration of the current ASR service, or
    // a specific model within the service.
    virtual ::grpc::Status GetRivaSpeechRecognitionConfig(::grpc::ClientContext* context, const ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest& request, ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse>> AsyncGetRivaSpeechRecognitionConfig(::grpc::ClientContext* context, const ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse>>(AsyncGetRivaSpeechRecognitionConfigRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse>> PrepareAsyncGetRivaSpeechRecognitionConfig(::grpc::ClientContext* context, const ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse>>(PrepareAsyncGetRivaSpeechRecognitionConfigRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Recognize expects a RecognizeRequest and returns a RecognizeResponse. This
      // request will block until the audio is uploaded, processed, and a transcript
      // is returned.
      virtual void Recognize(::grpc::ClientContext* context, const ::nvidia::riva::asr::RecognizeRequest* request, ::nvidia::riva::asr::RecognizeResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Recognize(::grpc::ClientContext* context, const ::nvidia::riva::asr::RecognizeRequest* request, ::nvidia::riva::asr::RecognizeResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // StreamingRecognize is a non-blocking API call that allows audio data to be
      // fed to the server in chunks as it becomes available. Depending on the
      // configuration in the StreamingRecognizeRequest, intermediate results can be
      // sent back to the client. Recognition ends when the stream is closed by the
      // client.
      virtual void StreamingRecognize(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::nvidia::riva::asr::StreamingRecognizeRequest,::nvidia::riva::asr::StreamingRecognizeResponse>* reactor) = 0;
      // Enables clients to request the configuration of the current ASR service, or
      // a specific model within the service.
      virtual void GetRivaSpeechRecognitionConfig(::grpc::ClientContext* context, const ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest* request, ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetRivaSpeechRecognitionConfig(::grpc::ClientContext* context, const ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest* request, ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::asr::RecognizeResponse>* AsyncRecognizeRaw(::grpc::ClientContext* context, const ::nvidia::riva::asr::RecognizeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::asr::RecognizeResponse>* PrepareAsyncRecognizeRaw(::grpc::ClientContext* context, const ::nvidia::riva::asr::RecognizeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::nvidia::riva::asr::StreamingRecognizeRequest, ::nvidia::riva::asr::StreamingRecognizeResponse>* StreamingRecognizeRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::nvidia::riva::asr::StreamingRecognizeRequest, ::nvidia::riva::asr::StreamingRecognizeResponse>* AsyncStreamingRecognizeRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::nvidia::riva::asr::StreamingRecognizeRequest, ::nvidia::riva::asr::StreamingRecognizeResponse>* PrepareAsyncStreamingRecognizeRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse>* AsyncGetRivaSpeechRecognitionConfigRaw(::grpc::ClientContext* context, const ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse>* PrepareAsyncGetRivaSpeechRecognitionConfigRaw(::grpc::ClientContext* context, const ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Recognize(::grpc::ClientContext* context, const ::nvidia::riva::asr::RecognizeRequest& request, ::nvidia::riva::asr::RecognizeResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia::riva::asr::RecognizeResponse>> AsyncRecognize(::grpc::ClientContext* context, const ::nvidia::riva::asr::RecognizeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia::riva::asr::RecognizeResponse>>(AsyncRecognizeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia::riva::asr::RecognizeResponse>> PrepareAsyncRecognize(::grpc::ClientContext* context, const ::nvidia::riva::asr::RecognizeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia::riva::asr::RecognizeResponse>>(PrepareAsyncRecognizeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::nvidia::riva::asr::StreamingRecognizeRequest, ::nvidia::riva::asr::StreamingRecognizeResponse>> StreamingRecognize(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::nvidia::riva::asr::StreamingRecognizeRequest, ::nvidia::riva::asr::StreamingRecognizeResponse>>(StreamingRecognizeRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::nvidia::riva::asr::StreamingRecognizeRequest, ::nvidia::riva::asr::StreamingRecognizeResponse>> AsyncStreamingRecognize(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::nvidia::riva::asr::StreamingRecognizeRequest, ::nvidia::riva::asr::StreamingRecognizeResponse>>(AsyncStreamingRecognizeRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::nvidia::riva::asr::StreamingRecognizeRequest, ::nvidia::riva::asr::StreamingRecognizeResponse>> PrepareAsyncStreamingRecognize(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::nvidia::riva::asr::StreamingRecognizeRequest, ::nvidia::riva::asr::StreamingRecognizeResponse>>(PrepareAsyncStreamingRecognizeRaw(context, cq));
    }
    ::grpc::Status GetRivaSpeechRecognitionConfig(::grpc::ClientContext* context, const ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest& request, ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse>> AsyncGetRivaSpeechRecognitionConfig(::grpc::ClientContext* context, const ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse>>(AsyncGetRivaSpeechRecognitionConfigRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse>> PrepareAsyncGetRivaSpeechRecognitionConfig(::grpc::ClientContext* context, const ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse>>(PrepareAsyncGetRivaSpeechRecognitionConfigRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Recognize(::grpc::ClientContext* context, const ::nvidia::riva::asr::RecognizeRequest* request, ::nvidia::riva::asr::RecognizeResponse* response, std::function<void(::grpc::Status)>) override;
      void Recognize(::grpc::ClientContext* context, const ::nvidia::riva::asr::RecognizeRequest* request, ::nvidia::riva::asr::RecognizeResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void StreamingRecognize(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::nvidia::riva::asr::StreamingRecognizeRequest,::nvidia::riva::asr::StreamingRecognizeResponse>* reactor) override;
      void GetRivaSpeechRecognitionConfig(::grpc::ClientContext* context, const ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest* request, ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse* response, std::function<void(::grpc::Status)>) override;
      void GetRivaSpeechRecognitionConfig(::grpc::ClientContext* context, const ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest* request, ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::nvidia::riva::asr::RecognizeResponse>* AsyncRecognizeRaw(::grpc::ClientContext* context, const ::nvidia::riva::asr::RecognizeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::nvidia::riva::asr::RecognizeResponse>* PrepareAsyncRecognizeRaw(::grpc::ClientContext* context, const ::nvidia::riva::asr::RecognizeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::nvidia::riva::asr::StreamingRecognizeRequest, ::nvidia::riva::asr::StreamingRecognizeResponse>* StreamingRecognizeRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::nvidia::riva::asr::StreamingRecognizeRequest, ::nvidia::riva::asr::StreamingRecognizeResponse>* AsyncStreamingRecognizeRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::nvidia::riva::asr::StreamingRecognizeRequest, ::nvidia::riva::asr::StreamingRecognizeResponse>* PrepareAsyncStreamingRecognizeRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse>* AsyncGetRivaSpeechRecognitionConfigRaw(::grpc::ClientContext* context, const ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse>* PrepareAsyncGetRivaSpeechRecognitionConfigRaw(::grpc::ClientContext* context, const ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Recognize_;
    const ::grpc::internal::RpcMethod rpcmethod_StreamingRecognize_;
    const ::grpc::internal::RpcMethod rpcmethod_GetRivaSpeechRecognitionConfig_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Recognize expects a RecognizeRequest and returns a RecognizeResponse. This
    // request will block until the audio is uploaded, processed, and a transcript
    // is returned.
    virtual ::grpc::Status Recognize(::grpc::ServerContext* context, const ::nvidia::riva::asr::RecognizeRequest* request, ::nvidia::riva::asr::RecognizeResponse* response);
    // StreamingRecognize is a non-blocking API call that allows audio data to be
    // fed to the server in chunks as it becomes available. Depending on the
    // configuration in the StreamingRecognizeRequest, intermediate results can be
    // sent back to the client. Recognition ends when the stream is closed by the
    // client.
    virtual ::grpc::Status StreamingRecognize(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::nvidia::riva::asr::StreamingRecognizeResponse, ::nvidia::riva::asr::StreamingRecognizeRequest>* stream);
    // Enables clients to request the configuration of the current ASR service, or
    // a specific model within the service.
    virtual ::grpc::Status GetRivaSpeechRecognitionConfig(::grpc::ServerContext* context, const ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest* request, ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Recognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Recognize() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Recognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recognize(::grpc::ServerContext* /*context*/, const ::nvidia::riva::asr::RecognizeRequest* /*request*/, ::nvidia::riva::asr::RecognizeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRecognize(::grpc::ServerContext* context, ::nvidia::riva::asr::RecognizeRequest* request, ::grpc::ServerAsyncResponseWriter< ::nvidia::riva::asr::RecognizeResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamingRecognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamingRecognize() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_StreamingRecognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamingRecognize(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::nvidia::riva::asr::StreamingRecognizeResponse, ::nvidia::riva::asr::StreamingRecognizeRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamingRecognize(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::nvidia::riva::asr::StreamingRecognizeResponse, ::nvidia::riva::asr::StreamingRecognizeRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetRivaSpeechRecognitionConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetRivaSpeechRecognitionConfig() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_GetRivaSpeechRecognitionConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRivaSpeechRecognitionConfig(::grpc::ServerContext* /*context*/, const ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest* /*request*/, ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetRivaSpeechRecognitionConfig(::grpc::ServerContext* context, ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest* request, ::grpc::ServerAsyncResponseWriter< ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Recognize<WithAsyncMethod_StreamingRecognize<WithAsyncMethod_GetRivaSpeechRecognitionConfig<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Recognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Recognize() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::nvidia::riva::asr::RecognizeRequest, ::nvidia::riva::asr::RecognizeResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::nvidia::riva::asr::RecognizeRequest* request, ::nvidia::riva::asr::RecognizeResponse* response) { return this->Recognize(context, request, response); }));}
    void SetMessageAllocatorFor_Recognize(
        ::grpc::MessageAllocator< ::nvidia::riva::asr::RecognizeRequest, ::nvidia::riva::asr::RecognizeResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::nvidia::riva::asr::RecognizeRequest, ::nvidia::riva::asr::RecognizeResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Recognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recognize(::grpc::ServerContext* /*context*/, const ::nvidia::riva::asr::RecognizeRequest* /*request*/, ::nvidia::riva::asr::RecognizeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Recognize(
      ::grpc::CallbackServerContext* /*context*/, const ::nvidia::riva::asr::RecognizeRequest* /*request*/, ::nvidia::riva::asr::RecognizeResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_StreamingRecognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamingRecognize() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackBidiHandler< ::nvidia::riva::asr::StreamingRecognizeRequest, ::nvidia::riva::asr::StreamingRecognizeResponse>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->StreamingRecognize(context); }));
    }
    ~WithCallbackMethod_StreamingRecognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamingRecognize(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::nvidia::riva::asr::StreamingRecognizeResponse, ::nvidia::riva::asr::StreamingRecognizeRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::nvidia::riva::asr::StreamingRecognizeRequest, ::nvidia::riva::asr::StreamingRecognizeResponse>* StreamingRecognize(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetRivaSpeechRecognitionConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetRivaSpeechRecognitionConfig() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest, ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest* request, ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse* response) { return this->GetRivaSpeechRecognitionConfig(context, request, response); }));}
    void SetMessageAllocatorFor_GetRivaSpeechRecognitionConfig(
        ::grpc::MessageAllocator< ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest, ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest, ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetRivaSpeechRecognitionConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRivaSpeechRecognitionConfig(::grpc::ServerContext* /*context*/, const ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest* /*request*/, ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetRivaSpeechRecognitionConfig(
      ::grpc::CallbackServerContext* /*context*/, const ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest* /*request*/, ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Recognize<WithCallbackMethod_StreamingRecognize<WithCallbackMethod_GetRivaSpeechRecognitionConfig<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Recognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Recognize() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Recognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recognize(::grpc::ServerContext* /*context*/, const ::nvidia::riva::asr::RecognizeRequest* /*request*/, ::nvidia::riva::asr::RecognizeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StreamingRecognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamingRecognize() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_StreamingRecognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamingRecognize(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::nvidia::riva::asr::StreamingRecognizeResponse, ::nvidia::riva::asr::StreamingRecognizeRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetRivaSpeechRecognitionConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetRivaSpeechRecognitionConfig() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_GetRivaSpeechRecognitionConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRivaSpeechRecognitionConfig(::grpc::ServerContext* /*context*/, const ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest* /*request*/, ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Recognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Recognize() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Recognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recognize(::grpc::ServerContext* /*context*/, const ::nvidia::riva::asr::RecognizeRequest* /*request*/, ::nvidia::riva::asr::RecognizeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRecognize(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamingRecognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamingRecognize() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_StreamingRecognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamingRecognize(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::nvidia::riva::asr::StreamingRecognizeResponse, ::nvidia::riva::asr::StreamingRecognizeRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamingRecognize(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetRivaSpeechRecognitionConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetRivaSpeechRecognitionConfig() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_GetRivaSpeechRecognitionConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRivaSpeechRecognitionConfig(::grpc::ServerContext* /*context*/, const ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest* /*request*/, ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetRivaSpeechRecognitionConfig(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Recognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Recognize() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Recognize(context, request, response); }));
    }
    ~WithRawCallbackMethod_Recognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recognize(::grpc::ServerContext* /*context*/, const ::nvidia::riva::asr::RecognizeRequest* /*request*/, ::nvidia::riva::asr::RecognizeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Recognize(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamingRecognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamingRecognize() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->StreamingRecognize(context); }));
    }
    ~WithRawCallbackMethod_StreamingRecognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamingRecognize(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::nvidia::riva::asr::StreamingRecognizeResponse, ::nvidia::riva::asr::StreamingRecognizeRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* StreamingRecognize(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetRivaSpeechRecognitionConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetRivaSpeechRecognitionConfig() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetRivaSpeechRecognitionConfig(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetRivaSpeechRecognitionConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRivaSpeechRecognitionConfig(::grpc::ServerContext* /*context*/, const ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest* /*request*/, ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetRivaSpeechRecognitionConfig(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Recognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Recognize() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::nvidia::riva::asr::RecognizeRequest, ::nvidia::riva::asr::RecognizeResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::nvidia::riva::asr::RecognizeRequest, ::nvidia::riva::asr::RecognizeResponse>* streamer) {
                       return this->StreamedRecognize(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Recognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Recognize(::grpc::ServerContext* /*context*/, const ::nvidia::riva::asr::RecognizeRequest* /*request*/, ::nvidia::riva::asr::RecognizeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRecognize(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::nvidia::riva::asr::RecognizeRequest,::nvidia::riva::asr::RecognizeResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetRivaSpeechRecognitionConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetRivaSpeechRecognitionConfig() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest, ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest, ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse>* streamer) {
                       return this->StreamedGetRivaSpeechRecognitionConfig(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetRivaSpeechRecognitionConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetRivaSpeechRecognitionConfig(::grpc::ServerContext* /*context*/, const ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest* /*request*/, ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetRivaSpeechRecognitionConfig(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest,::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Recognize<WithStreamedUnaryMethod_GetRivaSpeechRecognitionConfig<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Recognize<WithStreamedUnaryMethod_GetRivaSpeechRecognitionConfig<Service > > StreamedService;
};

}  // namespace asr
}  // namespace riva
}  // namespace nvidia


#endif  // GRPC_riva_2fproto_2friva_5fasr_2eproto__INCLUDED
