// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: riva/proto/riva_audio.proto
// Protobuf C++ Version: 4.25.0

#ifndef GOOGLE_PROTOBUF_INCLUDED_riva_2fproto_2friva_5faudio_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_riva_2fproto_2friva_5faudio_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025000 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_riva_2fproto_2friva_5faudio_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_riva_2fproto_2friva_5faudio_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_riva_2fproto_2friva_5faudio_2eproto;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace nvidia {
namespace riva {
enum AudioEncoding : int {
  ENCODING_UNSPECIFIED = 0,
  LINEAR_PCM = 1,
  FLAC = 2,
  MULAW = 3,
  OGGOPUS = 4,
  ALAW = 20,
  AudioEncoding_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  AudioEncoding_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool AudioEncoding_IsValid(int value);
extern const uint32_t AudioEncoding_internal_data_[];
constexpr AudioEncoding AudioEncoding_MIN = static_cast<AudioEncoding>(0);
constexpr AudioEncoding AudioEncoding_MAX = static_cast<AudioEncoding>(20);
constexpr int AudioEncoding_ARRAYSIZE = 20 + 1;
const ::google::protobuf::EnumDescriptor*
AudioEncoding_descriptor();
template <typename T>
const std::string& AudioEncoding_Name(T value) {
  static_assert(std::is_same<T, AudioEncoding>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to AudioEncoding_Name().");
  return ::google::protobuf::internal::NameOfEnum(AudioEncoding_descriptor(), value);
}
inline bool AudioEncoding_Parse(absl::string_view name, AudioEncoding* value) {
  return ::google::protobuf::internal::ParseNamedEnum<AudioEncoding>(
      AudioEncoding_descriptor(), name, value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace riva
}  // namespace nvidia


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::nvidia::riva::AudioEncoding> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::nvidia::riva::AudioEncoding>() {
  return ::nvidia::riva::AudioEncoding_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_riva_2fproto_2friva_5faudio_2eproto_2epb_2eh
