// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: riva/proto/riva_tts.proto
// Original file comments:
// SPDX-FileCopyrightText: Copyright (c) 2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: MIT
//
#ifndef GRPC_riva_2fproto_2friva_5ftts_2eproto__INCLUDED
#define GRPC_riva_2fproto_2friva_5ftts_2eproto__INCLUDED

#include "riva/proto/riva_tts.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace nvidia {
namespace riva {
namespace tts {

class RivaSpeechSynthesis final {
 public:
  static constexpr char const* service_full_name() {
    return "nvidia.riva.tts.RivaSpeechSynthesis";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Used to request text-to-speech from the service. Submit a request
    // containing the desired text and configuration, and receive audio bytes in
    // the requested format.
    virtual ::grpc::Status Synthesize(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest& request, ::nvidia::riva::tts::SynthesizeSpeechResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::tts::SynthesizeSpeechResponse>> AsyncSynthesize(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::tts::SynthesizeSpeechResponse>>(AsyncSynthesizeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::tts::SynthesizeSpeechResponse>> PrepareAsyncSynthesize(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::tts::SynthesizeSpeechResponse>>(PrepareAsyncSynthesizeRaw(context, request, cq));
    }
    // Used to request text-to-speech returned via stream as it becomes available.
    // Submit a SynthesizeSpeechRequest with desired text and configuration,
    // and receive stream of bytes in the requested format.
    std::unique_ptr< ::grpc::ClientReaderInterface< ::nvidia::riva::tts::SynthesizeSpeechResponse>> SynthesizeOnline(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::nvidia::riva::tts::SynthesizeSpeechResponse>>(SynthesizeOnlineRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::nvidia::riva::tts::SynthesizeSpeechResponse>> AsyncSynthesizeOnline(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::nvidia::riva::tts::SynthesizeSpeechResponse>>(AsyncSynthesizeOnlineRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::nvidia::riva::tts::SynthesizeSpeechResponse>> PrepareAsyncSynthesizeOnline(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::nvidia::riva::tts::SynthesizeSpeechResponse>>(PrepareAsyncSynthesizeOnlineRaw(context, request, cq));
    }
    // Enables clients to request the configuration of the current Synthesize
    // service, or a specific model within the service.
    virtual ::grpc::Status GetRivaSynthesisConfig(::grpc::ClientContext* context, const ::nvidia::riva::tts::RivaSynthesisConfigRequest& request, ::nvidia::riva::tts::RivaSynthesisConfigResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::tts::RivaSynthesisConfigResponse>> AsyncGetRivaSynthesisConfig(::grpc::ClientContext* context, const ::nvidia::riva::tts::RivaSynthesisConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::tts::RivaSynthesisConfigResponse>>(AsyncGetRivaSynthesisConfigRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::tts::RivaSynthesisConfigResponse>> PrepareAsyncGetRivaSynthesisConfig(::grpc::ClientContext* context, const ::nvidia::riva::tts::RivaSynthesisConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::tts::RivaSynthesisConfigResponse>>(PrepareAsyncGetRivaSynthesisConfigRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Used to request text-to-speech from the service. Submit a request
      // containing the desired text and configuration, and receive audio bytes in
      // the requested format.
      virtual void Synthesize(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest* request, ::nvidia::riva::tts::SynthesizeSpeechResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Synthesize(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest* request, ::nvidia::riva::tts::SynthesizeSpeechResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Used to request text-to-speech returned via stream as it becomes available.
      // Submit a SynthesizeSpeechRequest with desired text and configuration,
      // and receive stream of bytes in the requested format.
      virtual void SynthesizeOnline(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest* request, ::grpc::ClientReadReactor< ::nvidia::riva::tts::SynthesizeSpeechResponse>* reactor) = 0;
      // Enables clients to request the configuration of the current Synthesize
      // service, or a specific model within the service.
      virtual void GetRivaSynthesisConfig(::grpc::ClientContext* context, const ::nvidia::riva::tts::RivaSynthesisConfigRequest* request, ::nvidia::riva::tts::RivaSynthesisConfigResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetRivaSynthesisConfig(::grpc::ClientContext* context, const ::nvidia::riva::tts::RivaSynthesisConfigRequest* request, ::nvidia::riva::tts::RivaSynthesisConfigResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::tts::SynthesizeSpeechResponse>* AsyncSynthesizeRaw(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::tts::SynthesizeSpeechResponse>* PrepareAsyncSynthesizeRaw(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::nvidia::riva::tts::SynthesizeSpeechResponse>* SynthesizeOnlineRaw(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::nvidia::riva::tts::SynthesizeSpeechResponse>* AsyncSynthesizeOnlineRaw(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::nvidia::riva::tts::SynthesizeSpeechResponse>* PrepareAsyncSynthesizeOnlineRaw(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::tts::RivaSynthesisConfigResponse>* AsyncGetRivaSynthesisConfigRaw(::grpc::ClientContext* context, const ::nvidia::riva::tts::RivaSynthesisConfigRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::tts::RivaSynthesisConfigResponse>* PrepareAsyncGetRivaSynthesisConfigRaw(::grpc::ClientContext* context, const ::nvidia::riva::tts::RivaSynthesisConfigRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Synthesize(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest& request, ::nvidia::riva::tts::SynthesizeSpeechResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia::riva::tts::SynthesizeSpeechResponse>> AsyncSynthesize(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia::riva::tts::SynthesizeSpeechResponse>>(AsyncSynthesizeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia::riva::tts::SynthesizeSpeechResponse>> PrepareAsyncSynthesize(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia::riva::tts::SynthesizeSpeechResponse>>(PrepareAsyncSynthesizeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::nvidia::riva::tts::SynthesizeSpeechResponse>> SynthesizeOnline(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::nvidia::riva::tts::SynthesizeSpeechResponse>>(SynthesizeOnlineRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::nvidia::riva::tts::SynthesizeSpeechResponse>> AsyncSynthesizeOnline(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::nvidia::riva::tts::SynthesizeSpeechResponse>>(AsyncSynthesizeOnlineRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::nvidia::riva::tts::SynthesizeSpeechResponse>> PrepareAsyncSynthesizeOnline(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::nvidia::riva::tts::SynthesizeSpeechResponse>>(PrepareAsyncSynthesizeOnlineRaw(context, request, cq));
    }
    ::grpc::Status GetRivaSynthesisConfig(::grpc::ClientContext* context, const ::nvidia::riva::tts::RivaSynthesisConfigRequest& request, ::nvidia::riva::tts::RivaSynthesisConfigResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia::riva::tts::RivaSynthesisConfigResponse>> AsyncGetRivaSynthesisConfig(::grpc::ClientContext* context, const ::nvidia::riva::tts::RivaSynthesisConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia::riva::tts::RivaSynthesisConfigResponse>>(AsyncGetRivaSynthesisConfigRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia::riva::tts::RivaSynthesisConfigResponse>> PrepareAsyncGetRivaSynthesisConfig(::grpc::ClientContext* context, const ::nvidia::riva::tts::RivaSynthesisConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia::riva::tts::RivaSynthesisConfigResponse>>(PrepareAsyncGetRivaSynthesisConfigRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Synthesize(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest* request, ::nvidia::riva::tts::SynthesizeSpeechResponse* response, std::function<void(::grpc::Status)>) override;
      void Synthesize(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest* request, ::nvidia::riva::tts::SynthesizeSpeechResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SynthesizeOnline(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest* request, ::grpc::ClientReadReactor< ::nvidia::riva::tts::SynthesizeSpeechResponse>* reactor) override;
      void GetRivaSynthesisConfig(::grpc::ClientContext* context, const ::nvidia::riva::tts::RivaSynthesisConfigRequest* request, ::nvidia::riva::tts::RivaSynthesisConfigResponse* response, std::function<void(::grpc::Status)>) override;
      void GetRivaSynthesisConfig(::grpc::ClientContext* context, const ::nvidia::riva::tts::RivaSynthesisConfigRequest* request, ::nvidia::riva::tts::RivaSynthesisConfigResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::nvidia::riva::tts::SynthesizeSpeechResponse>* AsyncSynthesizeRaw(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::nvidia::riva::tts::SynthesizeSpeechResponse>* PrepareAsyncSynthesizeRaw(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::nvidia::riva::tts::SynthesizeSpeechResponse>* SynthesizeOnlineRaw(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest& request) override;
    ::grpc::ClientAsyncReader< ::nvidia::riva::tts::SynthesizeSpeechResponse>* AsyncSynthesizeOnlineRaw(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::nvidia::riva::tts::SynthesizeSpeechResponse>* PrepareAsyncSynthesizeOnlineRaw(::grpc::ClientContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::nvidia::riva::tts::RivaSynthesisConfigResponse>* AsyncGetRivaSynthesisConfigRaw(::grpc::ClientContext* context, const ::nvidia::riva::tts::RivaSynthesisConfigRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::nvidia::riva::tts::RivaSynthesisConfigResponse>* PrepareAsyncGetRivaSynthesisConfigRaw(::grpc::ClientContext* context, const ::nvidia::riva::tts::RivaSynthesisConfigRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Synthesize_;
    const ::grpc::internal::RpcMethod rpcmethod_SynthesizeOnline_;
    const ::grpc::internal::RpcMethod rpcmethod_GetRivaSynthesisConfig_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Used to request text-to-speech from the service. Submit a request
    // containing the desired text and configuration, and receive audio bytes in
    // the requested format.
    virtual ::grpc::Status Synthesize(::grpc::ServerContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest* request, ::nvidia::riva::tts::SynthesizeSpeechResponse* response);
    // Used to request text-to-speech returned via stream as it becomes available.
    // Submit a SynthesizeSpeechRequest with desired text and configuration,
    // and receive stream of bytes in the requested format.
    virtual ::grpc::Status SynthesizeOnline(::grpc::ServerContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest* request, ::grpc::ServerWriter< ::nvidia::riva::tts::SynthesizeSpeechResponse>* writer);
    // Enables clients to request the configuration of the current Synthesize
    // service, or a specific model within the service.
    virtual ::grpc::Status GetRivaSynthesisConfig(::grpc::ServerContext* context, const ::nvidia::riva::tts::RivaSynthesisConfigRequest* request, ::nvidia::riva::tts::RivaSynthesisConfigResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Synthesize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Synthesize() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Synthesize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Synthesize(::grpc::ServerContext* /*context*/, const ::nvidia::riva::tts::SynthesizeSpeechRequest* /*request*/, ::nvidia::riva::tts::SynthesizeSpeechResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSynthesize(::grpc::ServerContext* context, ::nvidia::riva::tts::SynthesizeSpeechRequest* request, ::grpc::ServerAsyncResponseWriter< ::nvidia::riva::tts::SynthesizeSpeechResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SynthesizeOnline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SynthesizeOnline() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_SynthesizeOnline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SynthesizeOnline(::grpc::ServerContext* /*context*/, const ::nvidia::riva::tts::SynthesizeSpeechRequest* /*request*/, ::grpc::ServerWriter< ::nvidia::riva::tts::SynthesizeSpeechResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSynthesizeOnline(::grpc::ServerContext* context, ::nvidia::riva::tts::SynthesizeSpeechRequest* request, ::grpc::ServerAsyncWriter< ::nvidia::riva::tts::SynthesizeSpeechResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetRivaSynthesisConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetRivaSynthesisConfig() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_GetRivaSynthesisConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRivaSynthesisConfig(::grpc::ServerContext* /*context*/, const ::nvidia::riva::tts::RivaSynthesisConfigRequest* /*request*/, ::nvidia::riva::tts::RivaSynthesisConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetRivaSynthesisConfig(::grpc::ServerContext* context, ::nvidia::riva::tts::RivaSynthesisConfigRequest* request, ::grpc::ServerAsyncResponseWriter< ::nvidia::riva::tts::RivaSynthesisConfigResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Synthesize<WithAsyncMethod_SynthesizeOnline<WithAsyncMethod_GetRivaSynthesisConfig<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Synthesize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Synthesize() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::nvidia::riva::tts::SynthesizeSpeechRequest, ::nvidia::riva::tts::SynthesizeSpeechResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest* request, ::nvidia::riva::tts::SynthesizeSpeechResponse* response) { return this->Synthesize(context, request, response); }));}
    void SetMessageAllocatorFor_Synthesize(
        ::grpc::MessageAllocator< ::nvidia::riva::tts::SynthesizeSpeechRequest, ::nvidia::riva::tts::SynthesizeSpeechResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::nvidia::riva::tts::SynthesizeSpeechRequest, ::nvidia::riva::tts::SynthesizeSpeechResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Synthesize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Synthesize(::grpc::ServerContext* /*context*/, const ::nvidia::riva::tts::SynthesizeSpeechRequest* /*request*/, ::nvidia::riva::tts::SynthesizeSpeechResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Synthesize(
      ::grpc::CallbackServerContext* /*context*/, const ::nvidia::riva::tts::SynthesizeSpeechRequest* /*request*/, ::nvidia::riva::tts::SynthesizeSpeechResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SynthesizeOnline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SynthesizeOnline() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::nvidia::riva::tts::SynthesizeSpeechRequest, ::nvidia::riva::tts::SynthesizeSpeechResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::nvidia::riva::tts::SynthesizeSpeechRequest* request) { return this->SynthesizeOnline(context, request); }));
    }
    ~WithCallbackMethod_SynthesizeOnline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SynthesizeOnline(::grpc::ServerContext* /*context*/, const ::nvidia::riva::tts::SynthesizeSpeechRequest* /*request*/, ::grpc::ServerWriter< ::nvidia::riva::tts::SynthesizeSpeechResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::nvidia::riva::tts::SynthesizeSpeechResponse>* SynthesizeOnline(
      ::grpc::CallbackServerContext* /*context*/, const ::nvidia::riva::tts::SynthesizeSpeechRequest* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetRivaSynthesisConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetRivaSynthesisConfig() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::nvidia::riva::tts::RivaSynthesisConfigRequest, ::nvidia::riva::tts::RivaSynthesisConfigResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::nvidia::riva::tts::RivaSynthesisConfigRequest* request, ::nvidia::riva::tts::RivaSynthesisConfigResponse* response) { return this->GetRivaSynthesisConfig(context, request, response); }));}
    void SetMessageAllocatorFor_GetRivaSynthesisConfig(
        ::grpc::MessageAllocator< ::nvidia::riva::tts::RivaSynthesisConfigRequest, ::nvidia::riva::tts::RivaSynthesisConfigResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::nvidia::riva::tts::RivaSynthesisConfigRequest, ::nvidia::riva::tts::RivaSynthesisConfigResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetRivaSynthesisConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRivaSynthesisConfig(::grpc::ServerContext* /*context*/, const ::nvidia::riva::tts::RivaSynthesisConfigRequest* /*request*/, ::nvidia::riva::tts::RivaSynthesisConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetRivaSynthesisConfig(
      ::grpc::CallbackServerContext* /*context*/, const ::nvidia::riva::tts::RivaSynthesisConfigRequest* /*request*/, ::nvidia::riva::tts::RivaSynthesisConfigResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Synthesize<WithCallbackMethod_SynthesizeOnline<WithCallbackMethod_GetRivaSynthesisConfig<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Synthesize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Synthesize() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Synthesize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Synthesize(::grpc::ServerContext* /*context*/, const ::nvidia::riva::tts::SynthesizeSpeechRequest* /*request*/, ::nvidia::riva::tts::SynthesizeSpeechResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SynthesizeOnline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SynthesizeOnline() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_SynthesizeOnline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SynthesizeOnline(::grpc::ServerContext* /*context*/, const ::nvidia::riva::tts::SynthesizeSpeechRequest* /*request*/, ::grpc::ServerWriter< ::nvidia::riva::tts::SynthesizeSpeechResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetRivaSynthesisConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetRivaSynthesisConfig() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_GetRivaSynthesisConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRivaSynthesisConfig(::grpc::ServerContext* /*context*/, const ::nvidia::riva::tts::RivaSynthesisConfigRequest* /*request*/, ::nvidia::riva::tts::RivaSynthesisConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Synthesize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Synthesize() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Synthesize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Synthesize(::grpc::ServerContext* /*context*/, const ::nvidia::riva::tts::SynthesizeSpeechRequest* /*request*/, ::nvidia::riva::tts::SynthesizeSpeechResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSynthesize(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SynthesizeOnline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SynthesizeOnline() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_SynthesizeOnline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SynthesizeOnline(::grpc::ServerContext* /*context*/, const ::nvidia::riva::tts::SynthesizeSpeechRequest* /*request*/, ::grpc::ServerWriter< ::nvidia::riva::tts::SynthesizeSpeechResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSynthesizeOnline(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetRivaSynthesisConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetRivaSynthesisConfig() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_GetRivaSynthesisConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRivaSynthesisConfig(::grpc::ServerContext* /*context*/, const ::nvidia::riva::tts::RivaSynthesisConfigRequest* /*request*/, ::nvidia::riva::tts::RivaSynthesisConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetRivaSynthesisConfig(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Synthesize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Synthesize() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Synthesize(context, request, response); }));
    }
    ~WithRawCallbackMethod_Synthesize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Synthesize(::grpc::ServerContext* /*context*/, const ::nvidia::riva::tts::SynthesizeSpeechRequest* /*request*/, ::nvidia::riva::tts::SynthesizeSpeechResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Synthesize(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SynthesizeOnline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SynthesizeOnline() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->SynthesizeOnline(context, request); }));
    }
    ~WithRawCallbackMethod_SynthesizeOnline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SynthesizeOnline(::grpc::ServerContext* /*context*/, const ::nvidia::riva::tts::SynthesizeSpeechRequest* /*request*/, ::grpc::ServerWriter< ::nvidia::riva::tts::SynthesizeSpeechResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* SynthesizeOnline(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetRivaSynthesisConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetRivaSynthesisConfig() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetRivaSynthesisConfig(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetRivaSynthesisConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRivaSynthesisConfig(::grpc::ServerContext* /*context*/, const ::nvidia::riva::tts::RivaSynthesisConfigRequest* /*request*/, ::nvidia::riva::tts::RivaSynthesisConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetRivaSynthesisConfig(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Synthesize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Synthesize() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::nvidia::riva::tts::SynthesizeSpeechRequest, ::nvidia::riva::tts::SynthesizeSpeechResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::nvidia::riva::tts::SynthesizeSpeechRequest, ::nvidia::riva::tts::SynthesizeSpeechResponse>* streamer) {
                       return this->StreamedSynthesize(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Synthesize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Synthesize(::grpc::ServerContext* /*context*/, const ::nvidia::riva::tts::SynthesizeSpeechRequest* /*request*/, ::nvidia::riva::tts::SynthesizeSpeechResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSynthesize(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::nvidia::riva::tts::SynthesizeSpeechRequest,::nvidia::riva::tts::SynthesizeSpeechResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetRivaSynthesisConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetRivaSynthesisConfig() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::nvidia::riva::tts::RivaSynthesisConfigRequest, ::nvidia::riva::tts::RivaSynthesisConfigResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::nvidia::riva::tts::RivaSynthesisConfigRequest, ::nvidia::riva::tts::RivaSynthesisConfigResponse>* streamer) {
                       return this->StreamedGetRivaSynthesisConfig(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetRivaSynthesisConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetRivaSynthesisConfig(::grpc::ServerContext* /*context*/, const ::nvidia::riva::tts::RivaSynthesisConfigRequest* /*request*/, ::nvidia::riva::tts::RivaSynthesisConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetRivaSynthesisConfig(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::nvidia::riva::tts::RivaSynthesisConfigRequest,::nvidia::riva::tts::RivaSynthesisConfigResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Synthesize<WithStreamedUnaryMethod_GetRivaSynthesisConfig<Service > > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_SynthesizeOnline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_SynthesizeOnline() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::nvidia::riva::tts::SynthesizeSpeechRequest, ::nvidia::riva::tts::SynthesizeSpeechResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::nvidia::riva::tts::SynthesizeSpeechRequest, ::nvidia::riva::tts::SynthesizeSpeechResponse>* streamer) {
                       return this->StreamedSynthesizeOnline(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_SynthesizeOnline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SynthesizeOnline(::grpc::ServerContext* /*context*/, const ::nvidia::riva::tts::SynthesizeSpeechRequest* /*request*/, ::grpc::ServerWriter< ::nvidia::riva::tts::SynthesizeSpeechResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedSynthesizeOnline(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::nvidia::riva::tts::SynthesizeSpeechRequest,::nvidia::riva::tts::SynthesizeSpeechResponse>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_SynthesizeOnline<Service > SplitStreamedService;
  typedef WithStreamedUnaryMethod_Synthesize<WithSplitStreamingMethod_SynthesizeOnline<WithStreamedUnaryMethod_GetRivaSynthesisConfig<Service > > > StreamedService;
};

}  // namespace tts
}  // namespace riva
}  // namespace nvidia


#endif  // GRPC_riva_2fproto_2friva_5ftts_2eproto__INCLUDED
