// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: riva/proto/riva_nlp.proto

#include "riva/proto/riva_nlp.pb.h"
#include "riva/proto/riva_nlp.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace nvidia {
namespace riva {
namespace nlp {

static const char* RivaLanguageUnderstanding_method_names[] = {
  "/nvidia.riva.nlp.RivaLanguageUnderstanding/ClassifyText",
  "/nvidia.riva.nlp.RivaLanguageUnderstanding/ClassifyTokens",
  "/nvidia.riva.nlp.RivaLanguageUnderstanding/TransformText",
  "/nvidia.riva.nlp.RivaLanguageUnderstanding/AnalyzeEntities",
  "/nvidia.riva.nlp.RivaLanguageUnderstanding/AnalyzeIntent",
  "/nvidia.riva.nlp.RivaLanguageUnderstanding/PunctuateText",
  "/nvidia.riva.nlp.RivaLanguageUnderstanding/NaturalQuery",
  "/nvidia.riva.nlp.RivaLanguageUnderstanding/GetRivaNLPConfig",
};

std::unique_ptr< RivaLanguageUnderstanding::Stub> RivaLanguageUnderstanding::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RivaLanguageUnderstanding::Stub> stub(new RivaLanguageUnderstanding::Stub(channel, options));
  return stub;
}

RivaLanguageUnderstanding::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ClassifyText_(RivaLanguageUnderstanding_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ClassifyTokens_(RivaLanguageUnderstanding_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_TransformText_(RivaLanguageUnderstanding_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AnalyzeEntities_(RivaLanguageUnderstanding_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AnalyzeIntent_(RivaLanguageUnderstanding_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PunctuateText_(RivaLanguageUnderstanding_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_NaturalQuery_(RivaLanguageUnderstanding_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetRivaNLPConfig_(RivaLanguageUnderstanding_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RivaLanguageUnderstanding::Stub::ClassifyText(::grpc::ClientContext* context, const ::nvidia::riva::nlp::TextClassRequest& request, ::nvidia::riva::nlp::TextClassResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::nvidia::riva::nlp::TextClassRequest, ::nvidia::riva::nlp::TextClassResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ClassifyText_, context, request, response);
}

void RivaLanguageUnderstanding::Stub::async::ClassifyText(::grpc::ClientContext* context, const ::nvidia::riva::nlp::TextClassRequest* request, ::nvidia::riva::nlp::TextClassResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::nvidia::riva::nlp::TextClassRequest, ::nvidia::riva::nlp::TextClassResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ClassifyText_, context, request, response, std::move(f));
}

void RivaLanguageUnderstanding::Stub::async::ClassifyText(::grpc::ClientContext* context, const ::nvidia::riva::nlp::TextClassRequest* request, ::nvidia::riva::nlp::TextClassResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ClassifyText_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::nvidia::riva::nlp::TextClassResponse>* RivaLanguageUnderstanding::Stub::PrepareAsyncClassifyTextRaw(::grpc::ClientContext* context, const ::nvidia::riva::nlp::TextClassRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::nvidia::riva::nlp::TextClassResponse, ::nvidia::riva::nlp::TextClassRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ClassifyText_, context, request);
}

::grpc::ClientAsyncResponseReader< ::nvidia::riva::nlp::TextClassResponse>* RivaLanguageUnderstanding::Stub::AsyncClassifyTextRaw(::grpc::ClientContext* context, const ::nvidia::riva::nlp::TextClassRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncClassifyTextRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RivaLanguageUnderstanding::Stub::ClassifyTokens(::grpc::ClientContext* context, const ::nvidia::riva::nlp::TokenClassRequest& request, ::nvidia::riva::nlp::TokenClassResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::nvidia::riva::nlp::TokenClassRequest, ::nvidia::riva::nlp::TokenClassResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ClassifyTokens_, context, request, response);
}

void RivaLanguageUnderstanding::Stub::async::ClassifyTokens(::grpc::ClientContext* context, const ::nvidia::riva::nlp::TokenClassRequest* request, ::nvidia::riva::nlp::TokenClassResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::nvidia::riva::nlp::TokenClassRequest, ::nvidia::riva::nlp::TokenClassResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ClassifyTokens_, context, request, response, std::move(f));
}

void RivaLanguageUnderstanding::Stub::async::ClassifyTokens(::grpc::ClientContext* context, const ::nvidia::riva::nlp::TokenClassRequest* request, ::nvidia::riva::nlp::TokenClassResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ClassifyTokens_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::nvidia::riva::nlp::TokenClassResponse>* RivaLanguageUnderstanding::Stub::PrepareAsyncClassifyTokensRaw(::grpc::ClientContext* context, const ::nvidia::riva::nlp::TokenClassRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::nvidia::riva::nlp::TokenClassResponse, ::nvidia::riva::nlp::TokenClassRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ClassifyTokens_, context, request);
}

::grpc::ClientAsyncResponseReader< ::nvidia::riva::nlp::TokenClassResponse>* RivaLanguageUnderstanding::Stub::AsyncClassifyTokensRaw(::grpc::ClientContext* context, const ::nvidia::riva::nlp::TokenClassRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncClassifyTokensRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RivaLanguageUnderstanding::Stub::TransformText(::grpc::ClientContext* context, const ::nvidia::riva::nlp::TextTransformRequest& request, ::nvidia::riva::nlp::TextTransformResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::nvidia::riva::nlp::TextTransformRequest, ::nvidia::riva::nlp::TextTransformResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_TransformText_, context, request, response);
}

void RivaLanguageUnderstanding::Stub::async::TransformText(::grpc::ClientContext* context, const ::nvidia::riva::nlp::TextTransformRequest* request, ::nvidia::riva::nlp::TextTransformResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::nvidia::riva::nlp::TextTransformRequest, ::nvidia::riva::nlp::TextTransformResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_TransformText_, context, request, response, std::move(f));
}

void RivaLanguageUnderstanding::Stub::async::TransformText(::grpc::ClientContext* context, const ::nvidia::riva::nlp::TextTransformRequest* request, ::nvidia::riva::nlp::TextTransformResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_TransformText_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::nvidia::riva::nlp::TextTransformResponse>* RivaLanguageUnderstanding::Stub::PrepareAsyncTransformTextRaw(::grpc::ClientContext* context, const ::nvidia::riva::nlp::TextTransformRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::nvidia::riva::nlp::TextTransformResponse, ::nvidia::riva::nlp::TextTransformRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_TransformText_, context, request);
}

::grpc::ClientAsyncResponseReader< ::nvidia::riva::nlp::TextTransformResponse>* RivaLanguageUnderstanding::Stub::AsyncTransformTextRaw(::grpc::ClientContext* context, const ::nvidia::riva::nlp::TextTransformRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncTransformTextRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RivaLanguageUnderstanding::Stub::AnalyzeEntities(::grpc::ClientContext* context, const ::nvidia::riva::nlp::AnalyzeEntitiesRequest& request, ::nvidia::riva::nlp::TokenClassResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::nvidia::riva::nlp::AnalyzeEntitiesRequest, ::nvidia::riva::nlp::TokenClassResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AnalyzeEntities_, context, request, response);
}

void RivaLanguageUnderstanding::Stub::async::AnalyzeEntities(::grpc::ClientContext* context, const ::nvidia::riva::nlp::AnalyzeEntitiesRequest* request, ::nvidia::riva::nlp::TokenClassResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::nvidia::riva::nlp::AnalyzeEntitiesRequest, ::nvidia::riva::nlp::TokenClassResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AnalyzeEntities_, context, request, response, std::move(f));
}

void RivaLanguageUnderstanding::Stub::async::AnalyzeEntities(::grpc::ClientContext* context, const ::nvidia::riva::nlp::AnalyzeEntitiesRequest* request, ::nvidia::riva::nlp::TokenClassResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AnalyzeEntities_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::nvidia::riva::nlp::TokenClassResponse>* RivaLanguageUnderstanding::Stub::PrepareAsyncAnalyzeEntitiesRaw(::grpc::ClientContext* context, const ::nvidia::riva::nlp::AnalyzeEntitiesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::nvidia::riva::nlp::TokenClassResponse, ::nvidia::riva::nlp::AnalyzeEntitiesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AnalyzeEntities_, context, request);
}

::grpc::ClientAsyncResponseReader< ::nvidia::riva::nlp::TokenClassResponse>* RivaLanguageUnderstanding::Stub::AsyncAnalyzeEntitiesRaw(::grpc::ClientContext* context, const ::nvidia::riva::nlp::AnalyzeEntitiesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAnalyzeEntitiesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RivaLanguageUnderstanding::Stub::AnalyzeIntent(::grpc::ClientContext* context, const ::nvidia::riva::nlp::AnalyzeIntentRequest& request, ::nvidia::riva::nlp::AnalyzeIntentResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::nvidia::riva::nlp::AnalyzeIntentRequest, ::nvidia::riva::nlp::AnalyzeIntentResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AnalyzeIntent_, context, request, response);
}

void RivaLanguageUnderstanding::Stub::async::AnalyzeIntent(::grpc::ClientContext* context, const ::nvidia::riva::nlp::AnalyzeIntentRequest* request, ::nvidia::riva::nlp::AnalyzeIntentResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::nvidia::riva::nlp::AnalyzeIntentRequest, ::nvidia::riva::nlp::AnalyzeIntentResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AnalyzeIntent_, context, request, response, std::move(f));
}

void RivaLanguageUnderstanding::Stub::async::AnalyzeIntent(::grpc::ClientContext* context, const ::nvidia::riva::nlp::AnalyzeIntentRequest* request, ::nvidia::riva::nlp::AnalyzeIntentResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AnalyzeIntent_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::nvidia::riva::nlp::AnalyzeIntentResponse>* RivaLanguageUnderstanding::Stub::PrepareAsyncAnalyzeIntentRaw(::grpc::ClientContext* context, const ::nvidia::riva::nlp::AnalyzeIntentRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::nvidia::riva::nlp::AnalyzeIntentResponse, ::nvidia::riva::nlp::AnalyzeIntentRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AnalyzeIntent_, context, request);
}

::grpc::ClientAsyncResponseReader< ::nvidia::riva::nlp::AnalyzeIntentResponse>* RivaLanguageUnderstanding::Stub::AsyncAnalyzeIntentRaw(::grpc::ClientContext* context, const ::nvidia::riva::nlp::AnalyzeIntentRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAnalyzeIntentRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RivaLanguageUnderstanding::Stub::PunctuateText(::grpc::ClientContext* context, const ::nvidia::riva::nlp::TextTransformRequest& request, ::nvidia::riva::nlp::TextTransformResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::nvidia::riva::nlp::TextTransformRequest, ::nvidia::riva::nlp::TextTransformResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PunctuateText_, context, request, response);
}

void RivaLanguageUnderstanding::Stub::async::PunctuateText(::grpc::ClientContext* context, const ::nvidia::riva::nlp::TextTransformRequest* request, ::nvidia::riva::nlp::TextTransformResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::nvidia::riva::nlp::TextTransformRequest, ::nvidia::riva::nlp::TextTransformResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PunctuateText_, context, request, response, std::move(f));
}

void RivaLanguageUnderstanding::Stub::async::PunctuateText(::grpc::ClientContext* context, const ::nvidia::riva::nlp::TextTransformRequest* request, ::nvidia::riva::nlp::TextTransformResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PunctuateText_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::nvidia::riva::nlp::TextTransformResponse>* RivaLanguageUnderstanding::Stub::PrepareAsyncPunctuateTextRaw(::grpc::ClientContext* context, const ::nvidia::riva::nlp::TextTransformRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::nvidia::riva::nlp::TextTransformResponse, ::nvidia::riva::nlp::TextTransformRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PunctuateText_, context, request);
}

::grpc::ClientAsyncResponseReader< ::nvidia::riva::nlp::TextTransformResponse>* RivaLanguageUnderstanding::Stub::AsyncPunctuateTextRaw(::grpc::ClientContext* context, const ::nvidia::riva::nlp::TextTransformRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPunctuateTextRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RivaLanguageUnderstanding::Stub::NaturalQuery(::grpc::ClientContext* context, const ::nvidia::riva::nlp::NaturalQueryRequest& request, ::nvidia::riva::nlp::NaturalQueryResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::nvidia::riva::nlp::NaturalQueryRequest, ::nvidia::riva::nlp::NaturalQueryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_NaturalQuery_, context, request, response);
}

void RivaLanguageUnderstanding::Stub::async::NaturalQuery(::grpc::ClientContext* context, const ::nvidia::riva::nlp::NaturalQueryRequest* request, ::nvidia::riva::nlp::NaturalQueryResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::nvidia::riva::nlp::NaturalQueryRequest, ::nvidia::riva::nlp::NaturalQueryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NaturalQuery_, context, request, response, std::move(f));
}

void RivaLanguageUnderstanding::Stub::async::NaturalQuery(::grpc::ClientContext* context, const ::nvidia::riva::nlp::NaturalQueryRequest* request, ::nvidia::riva::nlp::NaturalQueryResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NaturalQuery_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::nvidia::riva::nlp::NaturalQueryResponse>* RivaLanguageUnderstanding::Stub::PrepareAsyncNaturalQueryRaw(::grpc::ClientContext* context, const ::nvidia::riva::nlp::NaturalQueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::nvidia::riva::nlp::NaturalQueryResponse, ::nvidia::riva::nlp::NaturalQueryRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_NaturalQuery_, context, request);
}

::grpc::ClientAsyncResponseReader< ::nvidia::riva::nlp::NaturalQueryResponse>* RivaLanguageUnderstanding::Stub::AsyncNaturalQueryRaw(::grpc::ClientContext* context, const ::nvidia::riva::nlp::NaturalQueryRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncNaturalQueryRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RivaLanguageUnderstanding::Stub::GetRivaNLPConfig(::grpc::ClientContext* context, const ::nvidia::riva::nlp::RivaNLPConfigRequest& request, ::nvidia::riva::nlp::RivaNLPConfigResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::nvidia::riva::nlp::RivaNLPConfigRequest, ::nvidia::riva::nlp::RivaNLPConfigResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetRivaNLPConfig_, context, request, response);
}

void RivaLanguageUnderstanding::Stub::async::GetRivaNLPConfig(::grpc::ClientContext* context, const ::nvidia::riva::nlp::RivaNLPConfigRequest* request, ::nvidia::riva::nlp::RivaNLPConfigResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::nvidia::riva::nlp::RivaNLPConfigRequest, ::nvidia::riva::nlp::RivaNLPConfigResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRivaNLPConfig_, context, request, response, std::move(f));
}

void RivaLanguageUnderstanding::Stub::async::GetRivaNLPConfig(::grpc::ClientContext* context, const ::nvidia::riva::nlp::RivaNLPConfigRequest* request, ::nvidia::riva::nlp::RivaNLPConfigResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRivaNLPConfig_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::nvidia::riva::nlp::RivaNLPConfigResponse>* RivaLanguageUnderstanding::Stub::PrepareAsyncGetRivaNLPConfigRaw(::grpc::ClientContext* context, const ::nvidia::riva::nlp::RivaNLPConfigRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::nvidia::riva::nlp::RivaNLPConfigResponse, ::nvidia::riva::nlp::RivaNLPConfigRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetRivaNLPConfig_, context, request);
}

::grpc::ClientAsyncResponseReader< ::nvidia::riva::nlp::RivaNLPConfigResponse>* RivaLanguageUnderstanding::Stub::AsyncGetRivaNLPConfigRaw(::grpc::ClientContext* context, const ::nvidia::riva::nlp::RivaNLPConfigRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRivaNLPConfigRaw(context, request, cq);
  result->StartCall();
  return result;
}

RivaLanguageUnderstanding::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RivaLanguageUnderstanding_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RivaLanguageUnderstanding::Service, ::nvidia::riva::nlp::TextClassRequest, ::nvidia::riva::nlp::TextClassResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RivaLanguageUnderstanding::Service* service,
             ::grpc::ServerContext* ctx,
             const ::nvidia::riva::nlp::TextClassRequest* req,
             ::nvidia::riva::nlp::TextClassResponse* resp) {
               return service->ClassifyText(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RivaLanguageUnderstanding_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RivaLanguageUnderstanding::Service, ::nvidia::riva::nlp::TokenClassRequest, ::nvidia::riva::nlp::TokenClassResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RivaLanguageUnderstanding::Service* service,
             ::grpc::ServerContext* ctx,
             const ::nvidia::riva::nlp::TokenClassRequest* req,
             ::nvidia::riva::nlp::TokenClassResponse* resp) {
               return service->ClassifyTokens(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RivaLanguageUnderstanding_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RivaLanguageUnderstanding::Service, ::nvidia::riva::nlp::TextTransformRequest, ::nvidia::riva::nlp::TextTransformResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RivaLanguageUnderstanding::Service* service,
             ::grpc::ServerContext* ctx,
             const ::nvidia::riva::nlp::TextTransformRequest* req,
             ::nvidia::riva::nlp::TextTransformResponse* resp) {
               return service->TransformText(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RivaLanguageUnderstanding_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RivaLanguageUnderstanding::Service, ::nvidia::riva::nlp::AnalyzeEntitiesRequest, ::nvidia::riva::nlp::TokenClassResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RivaLanguageUnderstanding::Service* service,
             ::grpc::ServerContext* ctx,
             const ::nvidia::riva::nlp::AnalyzeEntitiesRequest* req,
             ::nvidia::riva::nlp::TokenClassResponse* resp) {
               return service->AnalyzeEntities(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RivaLanguageUnderstanding_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RivaLanguageUnderstanding::Service, ::nvidia::riva::nlp::AnalyzeIntentRequest, ::nvidia::riva::nlp::AnalyzeIntentResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RivaLanguageUnderstanding::Service* service,
             ::grpc::ServerContext* ctx,
             const ::nvidia::riva::nlp::AnalyzeIntentRequest* req,
             ::nvidia::riva::nlp::AnalyzeIntentResponse* resp) {
               return service->AnalyzeIntent(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RivaLanguageUnderstanding_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RivaLanguageUnderstanding::Service, ::nvidia::riva::nlp::TextTransformRequest, ::nvidia::riva::nlp::TextTransformResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RivaLanguageUnderstanding::Service* service,
             ::grpc::ServerContext* ctx,
             const ::nvidia::riva::nlp::TextTransformRequest* req,
             ::nvidia::riva::nlp::TextTransformResponse* resp) {
               return service->PunctuateText(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RivaLanguageUnderstanding_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RivaLanguageUnderstanding::Service, ::nvidia::riva::nlp::NaturalQueryRequest, ::nvidia::riva::nlp::NaturalQueryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RivaLanguageUnderstanding::Service* service,
             ::grpc::ServerContext* ctx,
             const ::nvidia::riva::nlp::NaturalQueryRequest* req,
             ::nvidia::riva::nlp::NaturalQueryResponse* resp) {
               return service->NaturalQuery(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RivaLanguageUnderstanding_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RivaLanguageUnderstanding::Service, ::nvidia::riva::nlp::RivaNLPConfigRequest, ::nvidia::riva::nlp::RivaNLPConfigResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RivaLanguageUnderstanding::Service* service,
             ::grpc::ServerContext* ctx,
             const ::nvidia::riva::nlp::RivaNLPConfigRequest* req,
             ::nvidia::riva::nlp::RivaNLPConfigResponse* resp) {
               return service->GetRivaNLPConfig(ctx, req, resp);
             }, this)));
}

RivaLanguageUnderstanding::Service::~Service() {
}

::grpc::Status RivaLanguageUnderstanding::Service::ClassifyText(::grpc::ServerContext* context, const ::nvidia::riva::nlp::TextClassRequest* request, ::nvidia::riva::nlp::TextClassResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RivaLanguageUnderstanding::Service::ClassifyTokens(::grpc::ServerContext* context, const ::nvidia::riva::nlp::TokenClassRequest* request, ::nvidia::riva::nlp::TokenClassResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RivaLanguageUnderstanding::Service::TransformText(::grpc::ServerContext* context, const ::nvidia::riva::nlp::TextTransformRequest* request, ::nvidia::riva::nlp::TextTransformResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RivaLanguageUnderstanding::Service::AnalyzeEntities(::grpc::ServerContext* context, const ::nvidia::riva::nlp::AnalyzeEntitiesRequest* request, ::nvidia::riva::nlp::TokenClassResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RivaLanguageUnderstanding::Service::AnalyzeIntent(::grpc::ServerContext* context, const ::nvidia::riva::nlp::AnalyzeIntentRequest* request, ::nvidia::riva::nlp::AnalyzeIntentResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RivaLanguageUnderstanding::Service::PunctuateText(::grpc::ServerContext* context, const ::nvidia::riva::nlp::TextTransformRequest* request, ::nvidia::riva::nlp::TextTransformResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RivaLanguageUnderstanding::Service::NaturalQuery(::grpc::ServerContext* context, const ::nvidia::riva::nlp::NaturalQueryRequest* request, ::nvidia::riva::nlp::NaturalQueryResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RivaLanguageUnderstanding::Service::GetRivaNLPConfig(::grpc::ServerContext* context, const ::nvidia::riva::nlp::RivaNLPConfigRequest* request, ::nvidia::riva::nlp::RivaNLPConfigResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace nvidia
}  // namespace riva
}  // namespace nlp

