// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: riva/proto/riva_asr.proto

#include "riva/proto/riva_asr.pb.h"
#include "riva/proto/riva_asr.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace nvidia {
namespace riva {
namespace asr {

static const char* RivaSpeechRecognition_method_names[] = {
  "/nvidia.riva.asr.RivaSpeechRecognition/Recognize",
  "/nvidia.riva.asr.RivaSpeechRecognition/StreamingRecognize",
  "/nvidia.riva.asr.RivaSpeechRecognition/GetRivaSpeechRecognitionConfig",
};

std::unique_ptr< RivaSpeechRecognition::Stub> RivaSpeechRecognition::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RivaSpeechRecognition::Stub> stub(new RivaSpeechRecognition::Stub(channel, options));
  return stub;
}

RivaSpeechRecognition::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Recognize_(RivaSpeechRecognition_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StreamingRecognize_(RivaSpeechRecognition_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_GetRivaSpeechRecognitionConfig_(RivaSpeechRecognition_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RivaSpeechRecognition::Stub::Recognize(::grpc::ClientContext* context, const ::nvidia::riva::asr::RecognizeRequest& request, ::nvidia::riva::asr::RecognizeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::nvidia::riva::asr::RecognizeRequest, ::nvidia::riva::asr::RecognizeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Recognize_, context, request, response);
}

void RivaSpeechRecognition::Stub::async::Recognize(::grpc::ClientContext* context, const ::nvidia::riva::asr::RecognizeRequest* request, ::nvidia::riva::asr::RecognizeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::nvidia::riva::asr::RecognizeRequest, ::nvidia::riva::asr::RecognizeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Recognize_, context, request, response, std::move(f));
}

void RivaSpeechRecognition::Stub::async::Recognize(::grpc::ClientContext* context, const ::nvidia::riva::asr::RecognizeRequest* request, ::nvidia::riva::asr::RecognizeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Recognize_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::nvidia::riva::asr::RecognizeResponse>* RivaSpeechRecognition::Stub::PrepareAsyncRecognizeRaw(::grpc::ClientContext* context, const ::nvidia::riva::asr::RecognizeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::nvidia::riva::asr::RecognizeResponse, ::nvidia::riva::asr::RecognizeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Recognize_, context, request);
}

::grpc::ClientAsyncResponseReader< ::nvidia::riva::asr::RecognizeResponse>* RivaSpeechRecognition::Stub::AsyncRecognizeRaw(::grpc::ClientContext* context, const ::nvidia::riva::asr::RecognizeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRecognizeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReaderWriter< ::nvidia::riva::asr::StreamingRecognizeRequest, ::nvidia::riva::asr::StreamingRecognizeResponse>* RivaSpeechRecognition::Stub::StreamingRecognizeRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::nvidia::riva::asr::StreamingRecognizeRequest, ::nvidia::riva::asr::StreamingRecognizeResponse>::Create(channel_.get(), rpcmethod_StreamingRecognize_, context);
}

void RivaSpeechRecognition::Stub::async::StreamingRecognize(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::nvidia::riva::asr::StreamingRecognizeRequest,::nvidia::riva::asr::StreamingRecognizeResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::nvidia::riva::asr::StreamingRecognizeRequest,::nvidia::riva::asr::StreamingRecognizeResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamingRecognize_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::nvidia::riva::asr::StreamingRecognizeRequest, ::nvidia::riva::asr::StreamingRecognizeResponse>* RivaSpeechRecognition::Stub::AsyncStreamingRecognizeRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::nvidia::riva::asr::StreamingRecognizeRequest, ::nvidia::riva::asr::StreamingRecognizeResponse>::Create(channel_.get(), cq, rpcmethod_StreamingRecognize_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::nvidia::riva::asr::StreamingRecognizeRequest, ::nvidia::riva::asr::StreamingRecognizeResponse>* RivaSpeechRecognition::Stub::PrepareAsyncStreamingRecognizeRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::nvidia::riva::asr::StreamingRecognizeRequest, ::nvidia::riva::asr::StreamingRecognizeResponse>::Create(channel_.get(), cq, rpcmethod_StreamingRecognize_, context, false, nullptr);
}

::grpc::Status RivaSpeechRecognition::Stub::GetRivaSpeechRecognitionConfig(::grpc::ClientContext* context, const ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest& request, ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest, ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetRivaSpeechRecognitionConfig_, context, request, response);
}

void RivaSpeechRecognition::Stub::async::GetRivaSpeechRecognitionConfig(::grpc::ClientContext* context, const ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest* request, ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest, ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRivaSpeechRecognitionConfig_, context, request, response, std::move(f));
}

void RivaSpeechRecognition::Stub::async::GetRivaSpeechRecognitionConfig(::grpc::ClientContext* context, const ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest* request, ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRivaSpeechRecognitionConfig_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse>* RivaSpeechRecognition::Stub::PrepareAsyncGetRivaSpeechRecognitionConfigRaw(::grpc::ClientContext* context, const ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse, ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetRivaSpeechRecognitionConfig_, context, request);
}

::grpc::ClientAsyncResponseReader< ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse>* RivaSpeechRecognition::Stub::AsyncGetRivaSpeechRecognitionConfigRaw(::grpc::ClientContext* context, const ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRivaSpeechRecognitionConfigRaw(context, request, cq);
  result->StartCall();
  return result;
}

RivaSpeechRecognition::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RivaSpeechRecognition_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RivaSpeechRecognition::Service, ::nvidia::riva::asr::RecognizeRequest, ::nvidia::riva::asr::RecognizeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RivaSpeechRecognition::Service* service,
             ::grpc::ServerContext* ctx,
             const ::nvidia::riva::asr::RecognizeRequest* req,
             ::nvidia::riva::asr::RecognizeResponse* resp) {
               return service->Recognize(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RivaSpeechRecognition_method_names[1],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< RivaSpeechRecognition::Service, ::nvidia::riva::asr::StreamingRecognizeRequest, ::nvidia::riva::asr::StreamingRecognizeResponse>(
          [](RivaSpeechRecognition::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::nvidia::riva::asr::StreamingRecognizeResponse,
             ::nvidia::riva::asr::StreamingRecognizeRequest>* stream) {
               return service->StreamingRecognize(ctx, stream);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RivaSpeechRecognition_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RivaSpeechRecognition::Service, ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest, ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RivaSpeechRecognition::Service* service,
             ::grpc::ServerContext* ctx,
             const ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest* req,
             ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse* resp) {
               return service->GetRivaSpeechRecognitionConfig(ctx, req, resp);
             }, this)));
}

RivaSpeechRecognition::Service::~Service() {
}

::grpc::Status RivaSpeechRecognition::Service::Recognize(::grpc::ServerContext* context, const ::nvidia::riva::asr::RecognizeRequest* request, ::nvidia::riva::asr::RecognizeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RivaSpeechRecognition::Service::StreamingRecognize(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::nvidia::riva::asr::StreamingRecognizeResponse, ::nvidia::riva::asr::StreamingRecognizeRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RivaSpeechRecognition::Service::GetRivaSpeechRecognitionConfig(::grpc::ServerContext* context, const ::nvidia::riva::asr::RivaSpeechRecognitionConfigRequest* request, ::nvidia::riva::asr::RivaSpeechRecognitionConfigResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace nvidia
}  // namespace riva
}  // namespace asr

