// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: riva/proto/riva_nmt.proto

#include "riva/proto/riva_nmt.pb.h"
#include "riva/proto/riva_nmt.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace nvidia {
namespace riva {
namespace nmt {

static const char* RivaTranslation_method_names[] = {
  "/nvidia.riva.nmt.RivaTranslation/TranslateText",
  "/nvidia.riva.nmt.RivaTranslation/ListSupportedLanguagePairs",
  "/nvidia.riva.nmt.RivaTranslation/StreamingTranslateSpeechToText",
  "/nvidia.riva.nmt.RivaTranslation/StreamingTranslateSpeechToSpeech",
};

std::unique_ptr< RivaTranslation::Stub> RivaTranslation::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RivaTranslation::Stub> stub(new RivaTranslation::Stub(channel, options));
  return stub;
}

RivaTranslation::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_TranslateText_(RivaTranslation_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListSupportedLanguagePairs_(RivaTranslation_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StreamingTranslateSpeechToText_(RivaTranslation_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_StreamingTranslateSpeechToSpeech_(RivaTranslation_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::Status RivaTranslation::Stub::TranslateText(::grpc::ClientContext* context, const ::nvidia::riva::nmt::TranslateTextRequest& request, ::nvidia::riva::nmt::TranslateTextResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::nvidia::riva::nmt::TranslateTextRequest, ::nvidia::riva::nmt::TranslateTextResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_TranslateText_, context, request, response);
}

void RivaTranslation::Stub::async::TranslateText(::grpc::ClientContext* context, const ::nvidia::riva::nmt::TranslateTextRequest* request, ::nvidia::riva::nmt::TranslateTextResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::nvidia::riva::nmt::TranslateTextRequest, ::nvidia::riva::nmt::TranslateTextResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_TranslateText_, context, request, response, std::move(f));
}

void RivaTranslation::Stub::async::TranslateText(::grpc::ClientContext* context, const ::nvidia::riva::nmt::TranslateTextRequest* request, ::nvidia::riva::nmt::TranslateTextResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_TranslateText_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::nvidia::riva::nmt::TranslateTextResponse>* RivaTranslation::Stub::PrepareAsyncTranslateTextRaw(::grpc::ClientContext* context, const ::nvidia::riva::nmt::TranslateTextRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::nvidia::riva::nmt::TranslateTextResponse, ::nvidia::riva::nmt::TranslateTextRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_TranslateText_, context, request);
}

::grpc::ClientAsyncResponseReader< ::nvidia::riva::nmt::TranslateTextResponse>* RivaTranslation::Stub::AsyncTranslateTextRaw(::grpc::ClientContext* context, const ::nvidia::riva::nmt::TranslateTextRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncTranslateTextRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RivaTranslation::Stub::ListSupportedLanguagePairs(::grpc::ClientContext* context, const ::nvidia::riva::nmt::AvailableLanguageRequest& request, ::nvidia::riva::nmt::AvailableLanguageResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::nvidia::riva::nmt::AvailableLanguageRequest, ::nvidia::riva::nmt::AvailableLanguageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListSupportedLanguagePairs_, context, request, response);
}

void RivaTranslation::Stub::async::ListSupportedLanguagePairs(::grpc::ClientContext* context, const ::nvidia::riva::nmt::AvailableLanguageRequest* request, ::nvidia::riva::nmt::AvailableLanguageResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::nvidia::riva::nmt::AvailableLanguageRequest, ::nvidia::riva::nmt::AvailableLanguageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListSupportedLanguagePairs_, context, request, response, std::move(f));
}

void RivaTranslation::Stub::async::ListSupportedLanguagePairs(::grpc::ClientContext* context, const ::nvidia::riva::nmt::AvailableLanguageRequest* request, ::nvidia::riva::nmt::AvailableLanguageResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListSupportedLanguagePairs_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::nvidia::riva::nmt::AvailableLanguageResponse>* RivaTranslation::Stub::PrepareAsyncListSupportedLanguagePairsRaw(::grpc::ClientContext* context, const ::nvidia::riva::nmt::AvailableLanguageRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::nvidia::riva::nmt::AvailableLanguageResponse, ::nvidia::riva::nmt::AvailableLanguageRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListSupportedLanguagePairs_, context, request);
}

::grpc::ClientAsyncResponseReader< ::nvidia::riva::nmt::AvailableLanguageResponse>* RivaTranslation::Stub::AsyncListSupportedLanguagePairsRaw(::grpc::ClientContext* context, const ::nvidia::riva::nmt::AvailableLanguageRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListSupportedLanguagePairsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse>* RivaTranslation::Stub::StreamingTranslateSpeechToTextRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse>::Create(channel_.get(), rpcmethod_StreamingTranslateSpeechToText_, context);
}

void RivaTranslation::Stub::async::StreamingTranslateSpeechToText(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest,::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest,::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamingTranslateSpeechToText_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse>* RivaTranslation::Stub::AsyncStreamingTranslateSpeechToTextRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse>::Create(channel_.get(), cq, rpcmethod_StreamingTranslateSpeechToText_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse>* RivaTranslation::Stub::PrepareAsyncStreamingTranslateSpeechToTextRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse>::Create(channel_.get(), cq, rpcmethod_StreamingTranslateSpeechToText_, context, false, nullptr);
}

::grpc::ClientReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse>* RivaTranslation::Stub::StreamingTranslateSpeechToSpeechRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse>::Create(channel_.get(), rpcmethod_StreamingTranslateSpeechToSpeech_, context);
}

void RivaTranslation::Stub::async::StreamingTranslateSpeechToSpeech(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest,::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest,::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamingTranslateSpeechToSpeech_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse>* RivaTranslation::Stub::AsyncStreamingTranslateSpeechToSpeechRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse>::Create(channel_.get(), cq, rpcmethod_StreamingTranslateSpeechToSpeech_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse>* RivaTranslation::Stub::PrepareAsyncStreamingTranslateSpeechToSpeechRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse>::Create(channel_.get(), cq, rpcmethod_StreamingTranslateSpeechToSpeech_, context, false, nullptr);
}

RivaTranslation::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RivaTranslation_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RivaTranslation::Service, ::nvidia::riva::nmt::TranslateTextRequest, ::nvidia::riva::nmt::TranslateTextResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RivaTranslation::Service* service,
             ::grpc::ServerContext* ctx,
             const ::nvidia::riva::nmt::TranslateTextRequest* req,
             ::nvidia::riva::nmt::TranslateTextResponse* resp) {
               return service->TranslateText(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RivaTranslation_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RivaTranslation::Service, ::nvidia::riva::nmt::AvailableLanguageRequest, ::nvidia::riva::nmt::AvailableLanguageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RivaTranslation::Service* service,
             ::grpc::ServerContext* ctx,
             const ::nvidia::riva::nmt::AvailableLanguageRequest* req,
             ::nvidia::riva::nmt::AvailableLanguageResponse* resp) {
               return service->ListSupportedLanguagePairs(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RivaTranslation_method_names[2],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< RivaTranslation::Service, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse>(
          [](RivaTranslation::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse,
             ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest>* stream) {
               return service->StreamingTranslateSpeechToText(ctx, stream);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RivaTranslation_method_names[3],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< RivaTranslation::Service, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse>(
          [](RivaTranslation::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse,
             ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest>* stream) {
               return service->StreamingTranslateSpeechToSpeech(ctx, stream);
             }, this)));
}

RivaTranslation::Service::~Service() {
}

::grpc::Status RivaTranslation::Service::TranslateText(::grpc::ServerContext* context, const ::nvidia::riva::nmt::TranslateTextRequest* request, ::nvidia::riva::nmt::TranslateTextResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RivaTranslation::Service::ListSupportedLanguagePairs(::grpc::ServerContext* context, const ::nvidia::riva::nmt::AvailableLanguageRequest* request, ::nvidia::riva::nmt::AvailableLanguageResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RivaTranslation::Service::StreamingTranslateSpeechToText(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RivaTranslation::Service::StreamingTranslateSpeechToSpeech(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace nvidia
}  // namespace riva
}  // namespace nmt

