// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: riva/proto/riva_nmt.proto
// Original file comments:
// Copyright (c) 2022, NVIDIA CORPORATION.  All rights reserved.
//
// NVIDIA CORPORATION and its licensors retain all intellectual property
// and proprietary rights in and to this software, related documentation
// and any modifications thereto.  Any use, reproduction, disclosure or
// distribution of this software and related documentation without an express
// license agreement from NVIDIA CORPORATION is strictly prohibited.
//
#ifndef GRPC_riva_2fproto_2friva_5fnmt_2eproto__INCLUDED
#define GRPC_riva_2fproto_2friva_5fnmt_2eproto__INCLUDED

#include "riva/proto/riva_nmt.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace nvidia {
namespace riva {
namespace nmt {

//
//  RivaTranslation service provides rpcs to translate between languages.
//
class RivaTranslation final {
 public:
  static constexpr char const* service_full_name() {
    return "nvidia.riva.nmt.RivaTranslation";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Translate text to text, from a source to a target language.  Currently
    // source and target language fields is required, along with the model name.
    // Multiple texts may be passed per request up to the given batch size for the
    // model, which is set at translation pipeline creation time.
    virtual ::grpc::Status TranslateText(::grpc::ClientContext* context, const ::nvidia::riva::nmt::TranslateTextRequest& request, ::nvidia::riva::nmt::TranslateTextResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::nmt::TranslateTextResponse>> AsyncTranslateText(::grpc::ClientContext* context, const ::nvidia::riva::nmt::TranslateTextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::nmt::TranslateTextResponse>>(AsyncTranslateTextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::nmt::TranslateTextResponse>> PrepareAsyncTranslateText(::grpc::ClientContext* context, const ::nvidia::riva::nmt::TranslateTextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::nmt::TranslateTextResponse>>(PrepareAsyncTranslateTextRaw(context, request, cq));
    }
    // Lists the available language pairs and models names to be used for
    // TranslateText
    virtual ::grpc::Status ListSupportedLanguagePairs(::grpc::ClientContext* context, const ::nvidia::riva::nmt::AvailableLanguageRequest& request, ::nvidia::riva::nmt::AvailableLanguageResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::nmt::AvailableLanguageResponse>> AsyncListSupportedLanguagePairs(::grpc::ClientContext* context, const ::nvidia::riva::nmt::AvailableLanguageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::nmt::AvailableLanguageResponse>>(AsyncListSupportedLanguagePairsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::nmt::AvailableLanguageResponse>> PrepareAsyncListSupportedLanguagePairs(::grpc::ClientContext* context, const ::nvidia::riva::nmt::AvailableLanguageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::nmt::AvailableLanguageResponse>>(PrepareAsyncListSupportedLanguagePairsRaw(context, request, cq));
    }
    // streaming speech to text translation api.
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse>> StreamingTranslateSpeechToText(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse>>(StreamingTranslateSpeechToTextRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse>> AsyncStreamingTranslateSpeechToText(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse>>(AsyncStreamingTranslateSpeechToTextRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse>> PrepareAsyncStreamingTranslateSpeechToText(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse>>(PrepareAsyncStreamingTranslateSpeechToTextRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse>> StreamingTranslateSpeechToSpeech(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse>>(StreamingTranslateSpeechToSpeechRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse>> AsyncStreamingTranslateSpeechToSpeech(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse>>(AsyncStreamingTranslateSpeechToSpeechRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse>> PrepareAsyncStreamingTranslateSpeechToSpeech(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse>>(PrepareAsyncStreamingTranslateSpeechToSpeechRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Translate text to text, from a source to a target language.  Currently
      // source and target language fields is required, along with the model name.
      // Multiple texts may be passed per request up to the given batch size for the
      // model, which is set at translation pipeline creation time.
      virtual void TranslateText(::grpc::ClientContext* context, const ::nvidia::riva::nmt::TranslateTextRequest* request, ::nvidia::riva::nmt::TranslateTextResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void TranslateText(::grpc::ClientContext* context, const ::nvidia::riva::nmt::TranslateTextRequest* request, ::nvidia::riva::nmt::TranslateTextResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Lists the available language pairs and models names to be used for
      // TranslateText
      virtual void ListSupportedLanguagePairs(::grpc::ClientContext* context, const ::nvidia::riva::nmt::AvailableLanguageRequest* request, ::nvidia::riva::nmt::AvailableLanguageResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ListSupportedLanguagePairs(::grpc::ClientContext* context, const ::nvidia::riva::nmt::AvailableLanguageRequest* request, ::nvidia::riva::nmt::AvailableLanguageResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // streaming speech to text translation api.
      virtual void StreamingTranslateSpeechToText(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest,::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse>* reactor) = 0;
      virtual void StreamingTranslateSpeechToSpeech(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest,::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::nmt::TranslateTextResponse>* AsyncTranslateTextRaw(::grpc::ClientContext* context, const ::nvidia::riva::nmt::TranslateTextRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::nmt::TranslateTextResponse>* PrepareAsyncTranslateTextRaw(::grpc::ClientContext* context, const ::nvidia::riva::nmt::TranslateTextRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::nmt::AvailableLanguageResponse>* AsyncListSupportedLanguagePairsRaw(::grpc::ClientContext* context, const ::nvidia::riva::nmt::AvailableLanguageRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nvidia::riva::nmt::AvailableLanguageResponse>* PrepareAsyncListSupportedLanguagePairsRaw(::grpc::ClientContext* context, const ::nvidia::riva::nmt::AvailableLanguageRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse>* StreamingTranslateSpeechToTextRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse>* AsyncStreamingTranslateSpeechToTextRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse>* PrepareAsyncStreamingTranslateSpeechToTextRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse>* StreamingTranslateSpeechToSpeechRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse>* AsyncStreamingTranslateSpeechToSpeechRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse>* PrepareAsyncStreamingTranslateSpeechToSpeechRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status TranslateText(::grpc::ClientContext* context, const ::nvidia::riva::nmt::TranslateTextRequest& request, ::nvidia::riva::nmt::TranslateTextResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia::riva::nmt::TranslateTextResponse>> AsyncTranslateText(::grpc::ClientContext* context, const ::nvidia::riva::nmt::TranslateTextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia::riva::nmt::TranslateTextResponse>>(AsyncTranslateTextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia::riva::nmt::TranslateTextResponse>> PrepareAsyncTranslateText(::grpc::ClientContext* context, const ::nvidia::riva::nmt::TranslateTextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia::riva::nmt::TranslateTextResponse>>(PrepareAsyncTranslateTextRaw(context, request, cq));
    }
    ::grpc::Status ListSupportedLanguagePairs(::grpc::ClientContext* context, const ::nvidia::riva::nmt::AvailableLanguageRequest& request, ::nvidia::riva::nmt::AvailableLanguageResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia::riva::nmt::AvailableLanguageResponse>> AsyncListSupportedLanguagePairs(::grpc::ClientContext* context, const ::nvidia::riva::nmt::AvailableLanguageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia::riva::nmt::AvailableLanguageResponse>>(AsyncListSupportedLanguagePairsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia::riva::nmt::AvailableLanguageResponse>> PrepareAsyncListSupportedLanguagePairs(::grpc::ClientContext* context, const ::nvidia::riva::nmt::AvailableLanguageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia::riva::nmt::AvailableLanguageResponse>>(PrepareAsyncListSupportedLanguagePairsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse>> StreamingTranslateSpeechToText(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse>>(StreamingTranslateSpeechToTextRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse>> AsyncStreamingTranslateSpeechToText(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse>>(AsyncStreamingTranslateSpeechToTextRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse>> PrepareAsyncStreamingTranslateSpeechToText(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse>>(PrepareAsyncStreamingTranslateSpeechToTextRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse>> StreamingTranslateSpeechToSpeech(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse>>(StreamingTranslateSpeechToSpeechRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse>> AsyncStreamingTranslateSpeechToSpeech(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse>>(AsyncStreamingTranslateSpeechToSpeechRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse>> PrepareAsyncStreamingTranslateSpeechToSpeech(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse>>(PrepareAsyncStreamingTranslateSpeechToSpeechRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void TranslateText(::grpc::ClientContext* context, const ::nvidia::riva::nmt::TranslateTextRequest* request, ::nvidia::riva::nmt::TranslateTextResponse* response, std::function<void(::grpc::Status)>) override;
      void TranslateText(::grpc::ClientContext* context, const ::nvidia::riva::nmt::TranslateTextRequest* request, ::nvidia::riva::nmt::TranslateTextResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ListSupportedLanguagePairs(::grpc::ClientContext* context, const ::nvidia::riva::nmt::AvailableLanguageRequest* request, ::nvidia::riva::nmt::AvailableLanguageResponse* response, std::function<void(::grpc::Status)>) override;
      void ListSupportedLanguagePairs(::grpc::ClientContext* context, const ::nvidia::riva::nmt::AvailableLanguageRequest* request, ::nvidia::riva::nmt::AvailableLanguageResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void StreamingTranslateSpeechToText(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest,::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse>* reactor) override;
      void StreamingTranslateSpeechToSpeech(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest,::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::nvidia::riva::nmt::TranslateTextResponse>* AsyncTranslateTextRaw(::grpc::ClientContext* context, const ::nvidia::riva::nmt::TranslateTextRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::nvidia::riva::nmt::TranslateTextResponse>* PrepareAsyncTranslateTextRaw(::grpc::ClientContext* context, const ::nvidia::riva::nmt::TranslateTextRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::nvidia::riva::nmt::AvailableLanguageResponse>* AsyncListSupportedLanguagePairsRaw(::grpc::ClientContext* context, const ::nvidia::riva::nmt::AvailableLanguageRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::nvidia::riva::nmt::AvailableLanguageResponse>* PrepareAsyncListSupportedLanguagePairsRaw(::grpc::ClientContext* context, const ::nvidia::riva::nmt::AvailableLanguageRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse>* StreamingTranslateSpeechToTextRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse>* AsyncStreamingTranslateSpeechToTextRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse>* PrepareAsyncStreamingTranslateSpeechToTextRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse>* StreamingTranslateSpeechToSpeechRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse>* AsyncStreamingTranslateSpeechToSpeechRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse>* PrepareAsyncStreamingTranslateSpeechToSpeechRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_TranslateText_;
    const ::grpc::internal::RpcMethod rpcmethod_ListSupportedLanguagePairs_;
    const ::grpc::internal::RpcMethod rpcmethod_StreamingTranslateSpeechToText_;
    const ::grpc::internal::RpcMethod rpcmethod_StreamingTranslateSpeechToSpeech_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Translate text to text, from a source to a target language.  Currently
    // source and target language fields is required, along with the model name.
    // Multiple texts may be passed per request up to the given batch size for the
    // model, which is set at translation pipeline creation time.
    virtual ::grpc::Status TranslateText(::grpc::ServerContext* context, const ::nvidia::riva::nmt::TranslateTextRequest* request, ::nvidia::riva::nmt::TranslateTextResponse* response);
    // Lists the available language pairs and models names to be used for
    // TranslateText
    virtual ::grpc::Status ListSupportedLanguagePairs(::grpc::ServerContext* context, const ::nvidia::riva::nmt::AvailableLanguageRequest* request, ::nvidia::riva::nmt::AvailableLanguageResponse* response);
    // streaming speech to text translation api.
    virtual ::grpc::Status StreamingTranslateSpeechToText(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest>* stream);
    virtual ::grpc::Status StreamingTranslateSpeechToSpeech(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_TranslateText : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_TranslateText() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_TranslateText() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TranslateText(::grpc::ServerContext* /*context*/, const ::nvidia::riva::nmt::TranslateTextRequest* /*request*/, ::nvidia::riva::nmt::TranslateTextResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTranslateText(::grpc::ServerContext* context, ::nvidia::riva::nmt::TranslateTextRequest* request, ::grpc::ServerAsyncResponseWriter< ::nvidia::riva::nmt::TranslateTextResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ListSupportedLanguagePairs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListSupportedLanguagePairs() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ListSupportedLanguagePairs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListSupportedLanguagePairs(::grpc::ServerContext* /*context*/, const ::nvidia::riva::nmt::AvailableLanguageRequest* /*request*/, ::nvidia::riva::nmt::AvailableLanguageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListSupportedLanguagePairs(::grpc::ServerContext* context, ::nvidia::riva::nmt::AvailableLanguageRequest* request, ::grpc::ServerAsyncResponseWriter< ::nvidia::riva::nmt::AvailableLanguageResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamingTranslateSpeechToText : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamingTranslateSpeechToText() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_StreamingTranslateSpeechToText() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamingTranslateSpeechToText(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamingTranslateSpeechToText(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(2, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamingTranslateSpeechToSpeech : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamingTranslateSpeechToSpeech() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_StreamingTranslateSpeechToSpeech() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamingTranslateSpeechToSpeech(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamingTranslateSpeechToSpeech(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(3, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_TranslateText<WithAsyncMethod_ListSupportedLanguagePairs<WithAsyncMethod_StreamingTranslateSpeechToText<WithAsyncMethod_StreamingTranslateSpeechToSpeech<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_TranslateText : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_TranslateText() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::nvidia::riva::nmt::TranslateTextRequest, ::nvidia::riva::nmt::TranslateTextResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::nvidia::riva::nmt::TranslateTextRequest* request, ::nvidia::riva::nmt::TranslateTextResponse* response) { return this->TranslateText(context, request, response); }));}
    void SetMessageAllocatorFor_TranslateText(
        ::grpc::MessageAllocator< ::nvidia::riva::nmt::TranslateTextRequest, ::nvidia::riva::nmt::TranslateTextResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::nvidia::riva::nmt::TranslateTextRequest, ::nvidia::riva::nmt::TranslateTextResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_TranslateText() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TranslateText(::grpc::ServerContext* /*context*/, const ::nvidia::riva::nmt::TranslateTextRequest* /*request*/, ::nvidia::riva::nmt::TranslateTextResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* TranslateText(
      ::grpc::CallbackServerContext* /*context*/, const ::nvidia::riva::nmt::TranslateTextRequest* /*request*/, ::nvidia::riva::nmt::TranslateTextResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ListSupportedLanguagePairs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListSupportedLanguagePairs() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::nvidia::riva::nmt::AvailableLanguageRequest, ::nvidia::riva::nmt::AvailableLanguageResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::nvidia::riva::nmt::AvailableLanguageRequest* request, ::nvidia::riva::nmt::AvailableLanguageResponse* response) { return this->ListSupportedLanguagePairs(context, request, response); }));}
    void SetMessageAllocatorFor_ListSupportedLanguagePairs(
        ::grpc::MessageAllocator< ::nvidia::riva::nmt::AvailableLanguageRequest, ::nvidia::riva::nmt::AvailableLanguageResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::nvidia::riva::nmt::AvailableLanguageRequest, ::nvidia::riva::nmt::AvailableLanguageResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ListSupportedLanguagePairs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListSupportedLanguagePairs(::grpc::ServerContext* /*context*/, const ::nvidia::riva::nmt::AvailableLanguageRequest* /*request*/, ::nvidia::riva::nmt::AvailableLanguageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListSupportedLanguagePairs(
      ::grpc::CallbackServerContext* /*context*/, const ::nvidia::riva::nmt::AvailableLanguageRequest* /*request*/, ::nvidia::riva::nmt::AvailableLanguageResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_StreamingTranslateSpeechToText : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamingTranslateSpeechToText() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackBidiHandler< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->StreamingTranslateSpeechToText(context); }));
    }
    ~WithCallbackMethod_StreamingTranslateSpeechToText() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamingTranslateSpeechToText(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse>* StreamingTranslateSpeechToText(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_StreamingTranslateSpeechToSpeech : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamingTranslateSpeechToSpeech() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackBidiHandler< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->StreamingTranslateSpeechToSpeech(context); }));
    }
    ~WithCallbackMethod_StreamingTranslateSpeechToSpeech() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamingTranslateSpeechToSpeech(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse>* StreamingTranslateSpeechToSpeech(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_TranslateText<WithCallbackMethod_ListSupportedLanguagePairs<WithCallbackMethod_StreamingTranslateSpeechToText<WithCallbackMethod_StreamingTranslateSpeechToSpeech<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_TranslateText : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_TranslateText() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_TranslateText() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TranslateText(::grpc::ServerContext* /*context*/, const ::nvidia::riva::nmt::TranslateTextRequest* /*request*/, ::nvidia::riva::nmt::TranslateTextResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ListSupportedLanguagePairs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListSupportedLanguagePairs() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ListSupportedLanguagePairs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListSupportedLanguagePairs(::grpc::ServerContext* /*context*/, const ::nvidia::riva::nmt::AvailableLanguageRequest* /*request*/, ::nvidia::riva::nmt::AvailableLanguageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StreamingTranslateSpeechToText : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamingTranslateSpeechToText() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_StreamingTranslateSpeechToText() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamingTranslateSpeechToText(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StreamingTranslateSpeechToSpeech : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamingTranslateSpeechToSpeech() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_StreamingTranslateSpeechToSpeech() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamingTranslateSpeechToSpeech(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_TranslateText : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_TranslateText() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_TranslateText() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TranslateText(::grpc::ServerContext* /*context*/, const ::nvidia::riva::nmt::TranslateTextRequest* /*request*/, ::nvidia::riva::nmt::TranslateTextResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTranslateText(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListSupportedLanguagePairs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListSupportedLanguagePairs() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ListSupportedLanguagePairs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListSupportedLanguagePairs(::grpc::ServerContext* /*context*/, const ::nvidia::riva::nmt::AvailableLanguageRequest* /*request*/, ::nvidia::riva::nmt::AvailableLanguageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListSupportedLanguagePairs(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamingTranslateSpeechToText : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamingTranslateSpeechToText() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_StreamingTranslateSpeechToText() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamingTranslateSpeechToText(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamingTranslateSpeechToText(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(2, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamingTranslateSpeechToSpeech : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamingTranslateSpeechToSpeech() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_StreamingTranslateSpeechToSpeech() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamingTranslateSpeechToSpeech(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamingTranslateSpeechToSpeech(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(3, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_TranslateText : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_TranslateText() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->TranslateText(context, request, response); }));
    }
    ~WithRawCallbackMethod_TranslateText() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TranslateText(::grpc::ServerContext* /*context*/, const ::nvidia::riva::nmt::TranslateTextRequest* /*request*/, ::nvidia::riva::nmt::TranslateTextResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* TranslateText(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListSupportedLanguagePairs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListSupportedLanguagePairs() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListSupportedLanguagePairs(context, request, response); }));
    }
    ~WithRawCallbackMethod_ListSupportedLanguagePairs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListSupportedLanguagePairs(::grpc::ServerContext* /*context*/, const ::nvidia::riva::nmt::AvailableLanguageRequest* /*request*/, ::nvidia::riva::nmt::AvailableLanguageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListSupportedLanguagePairs(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamingTranslateSpeechToText : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamingTranslateSpeechToText() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->StreamingTranslateSpeechToText(context); }));
    }
    ~WithRawCallbackMethod_StreamingTranslateSpeechToText() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamingTranslateSpeechToText(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToTextResponse, ::nvidia::riva::nmt::StreamingTranslateSpeechToTextRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* StreamingTranslateSpeechToText(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamingTranslateSpeechToSpeech : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamingTranslateSpeechToSpeech() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->StreamingTranslateSpeechToSpeech(context); }));
    }
    ~WithRawCallbackMethod_StreamingTranslateSpeechToSpeech() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamingTranslateSpeechToSpeech(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechResponse, ::nvidia::riva::nmt::StreamingTranslateSpeechToSpeechRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* StreamingTranslateSpeechToSpeech(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_TranslateText : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_TranslateText() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::nvidia::riva::nmt::TranslateTextRequest, ::nvidia::riva::nmt::TranslateTextResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::nvidia::riva::nmt::TranslateTextRequest, ::nvidia::riva::nmt::TranslateTextResponse>* streamer) {
                       return this->StreamedTranslateText(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_TranslateText() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status TranslateText(::grpc::ServerContext* /*context*/, const ::nvidia::riva::nmt::TranslateTextRequest* /*request*/, ::nvidia::riva::nmt::TranslateTextResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedTranslateText(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::nvidia::riva::nmt::TranslateTextRequest,::nvidia::riva::nmt::TranslateTextResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListSupportedLanguagePairs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListSupportedLanguagePairs() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::nvidia::riva::nmt::AvailableLanguageRequest, ::nvidia::riva::nmt::AvailableLanguageResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::nvidia::riva::nmt::AvailableLanguageRequest, ::nvidia::riva::nmt::AvailableLanguageResponse>* streamer) {
                       return this->StreamedListSupportedLanguagePairs(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListSupportedLanguagePairs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListSupportedLanguagePairs(::grpc::ServerContext* /*context*/, const ::nvidia::riva::nmt::AvailableLanguageRequest* /*request*/, ::nvidia::riva::nmt::AvailableLanguageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListSupportedLanguagePairs(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::nvidia::riva::nmt::AvailableLanguageRequest,::nvidia::riva::nmt::AvailableLanguageResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_TranslateText<WithStreamedUnaryMethod_ListSupportedLanguagePairs<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_TranslateText<WithStreamedUnaryMethod_ListSupportedLanguagePairs<Service > > StreamedService;
};

}  // namespace nmt
}  // namespace riva
}  // namespace nvidia


#endif  // GRPC_riva_2fproto_2friva_5fnmt_2eproto__INCLUDED
