// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: riva/proto/riva_audio.proto

#include "riva/proto/riva_audio.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace nvidia {
namespace riva {
}  // namespace riva
}  // namespace nvidia
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_riva_2fproto_2friva_5faudio_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_riva_2fproto_2friva_5faudio_2eproto = nullptr;
const ::uint32_t TableStruct_riva_2fproto_2friva_5faudio_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_riva_2fproto_2friva_5faudio_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\033riva/proto/riva_audio.proto\022\013nvidia.ri"
    "va*e\n\rAudioEncoding\022\030\n\024ENCODING_UNSPECIF"
    "IED\020\000\022\016\n\nLINEAR_PCM\020\001\022\010\n\004FLAC\020\002\022\t\n\005MULAW"
    "\020\003\022\013\n\007OGGOPUS\020\004\022\010\n\004ALAW\020\024B\033Z\026nvidia.com/"
    "riva_speech\370\001\001b\006proto3"
};
static ::absl::once_flag descriptor_table_riva_2fproto_2friva_5faudio_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_riva_2fproto_2friva_5faudio_2eproto = {
    false,
    false,
    182,
    descriptor_table_protodef_riva_2fproto_2friva_5faudio_2eproto,
    "riva/proto/riva_audio.proto",
    &descriptor_table_riva_2fproto_2friva_5faudio_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_riva_2fproto_2friva_5faudio_2eproto::offsets,
    nullptr,
    file_level_enum_descriptors_riva_2fproto_2friva_5faudio_2eproto,
    file_level_service_descriptors_riva_2fproto_2friva_5faudio_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_riva_2fproto_2friva_5faudio_2eproto_getter() {
  return &descriptor_table_riva_2fproto_2friva_5faudio_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_riva_2fproto_2friva_5faudio_2eproto(&descriptor_table_riva_2fproto_2friva_5faudio_2eproto);
namespace nvidia {
namespace riva {
const ::google::protobuf::EnumDescriptor* AudioEncoding_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_riva_2fproto_2friva_5faudio_2eproto);
  return file_level_enum_descriptors_riva_2fproto_2friva_5faudio_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t AudioEncoding_internal_data_[] = {
    327680u, 32u, 32768u, };
bool AudioEncoding_IsValid(int value) {
  return 0 <= value && value <= 20 && ((1048607u >> value) & 1) != 0;
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace riva
}  // namespace nvidia
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
